vuematerial/vue-material

README.md, package.json, yarn.lock
We need to be sure babel-cli is installed as it is required for dev.
=> Add babel-cli as dev dependecy

README.md, docs/src/pages/components/Switch.vue, src/components/mdSwitch/mdSwitch.vue
Hi, 
as button tag is set to `type="submit"` by default, it causes problems when the switch is placed in a `<form>`.
I thought that passing `type` (if needed) to the `md-switch` could be useful?
Thanks for your work!
=> Added 'type' props to switch button

src/components/mdInputContainer/common.js
i think the problem is: this.$el.value is sometime not set fast enough und you have to use vue.nextTick() https://vuejs.org/v2/api/#Vue-nextTick if you have to use the value of the input
=> use the internal value of md_input to set the value of the container

docs/src/pages/components/Menu.vue, src/components/mdMenu/mdMenu.vue
I needed a menu list that do not cover menu trigger. You can see how it should look at https://material.google.com/components/menus.html. I didn't bother to create issue for that.
I think the code is quite obvious but I have one concern about the API. I was wondering it it would be better to just add another direction constant strings (which I did) or maybe as another prop called "align" for this purpose. Also if you have better name for this feature I'm open for the change.
=> Add extra "align" directions that do not cover menu trigger.

src/core/components/mdInkRipple/index.js
The mdInkRipple-directive passes the elemnt as an param. But the param option is missing.
https://github.com/marcosmoura/vue-material/blob/master/src/core/components/mdInkRipple/index.js#L114
It's fix for #114 not #109 🙈
=> unregisterMouseEvent accepts the element as parameter

src/components/mdList/mdListItem.vue
Hi,
In MdListItem, we cannot handle the @click native-event because of the declaration of the listItemSpec. 
And then, we cannot do ``@click.self`` or others because the native event is always ``undefined``, this is the vue.js code generated when we add ``@click.self`` :
```javascript
on: {
"click": function($event) {
if ($event.target !== $event.currentTarget) { return; }
_vm.navigateToDetail(item)
}
}
```
The PR just send the $event on click event in items.
=> [fix] Handling md-list-item click

src/components/mdTable/mdTablePagination.vue
to display the right number , not always Numer.MAX_SAFE_INTEGER or
“false”
=> fix : tablePagination bug

src/core/components/mdTheme/index.js
Building was failing because `src/core/components/mdTheme/index.js` was trying to import `MdTheme` instead of `mdTheme`. My guess is you're on a case-insensitive filesystem, but for us linux folk it matters :)
If you want to just do this in your own commit, that's cool.
=> Fix mdTheme.vue filename case

src/components/mdSnackbar/mdSnackbar.vue
The title pretty much says it all, but `this.snackbarElement.querySelector('.md-ripple')` is null when an `md-button` is not included causing an error in the console.
=> check if .md-ripple exists (it doesn't if not using md-button)

src/components/mdInputContainer/common.js
It appears the watcher for `value` (in `common.js`) runs before the input's value has synced through the v-model. Thus when the watcher for `value` runs, the value provided to the function is the new value, and `this.$el.value` is still the old value.
In the case where the input value is non-`null` and you set the value to `null`, the function:
```
setParentValue(value) {
this.parentContainer.setValue(value || this.$el.value);
},
```
Actually sets the parent value to the old value (since `value` is `null` and `this.$el.value` is still the old non-`null` value.) This means the parent sees the old value, it's `hasValue` is computed as true, and the `md-has-value` class is still applied, leaving the label above the input instead of in it as a placeholder.
This PR just explicitly sets …
=> fixes md-input-container label bug #277

src/components/mdFile/mdFile.vue
This sets the v-model to null when the Cancel button is selected in the file picker to match the default browser behavior.
=> fixes #290 - set filename even when null

docs/src/pages/components/BottomBar.vue, src/components/mdBottomBar/mdBottomBar.vue, src/components/mdBottomBar/mdBottomBarItem.vue
Now we fire off an event when the active item changes, just like `mdTabs`. Additionally, this moves activation logic to `mdBottomBar`, instead of each `mdBottomBarItem`. It made the change easier to implement, and seems a bit cleaner, though that's subjective.
The primary motivation for this is to better match `mdTabs`, and to make `mdBottomBar` a bit easier to work with.
=> Added 'change' event to mdBottomBar.

.gitignore, docs/src/pages/ui-elements/Layout.vue, src/components/mdLayout/mdLayout.scss, src/components/mdLayout/mdLayout.vue, src/core/stylesheets/mixins.scss
Currently there is no way to hide an element on a breakpoint and above, eg.: medium size and above. Given this issue, a good enhancement would be having some responsive classes. I created and I'm proposing the following classes:
```scss
md-hide-#{type}-and-up
```
Where **#{type}** can be: xsmall, small, medium, large, xlarge.
The media queries that controls those classes are:
```scss
@mixin layout-xsmall-and-up {
@media (min-width: #{$breakpoint-xsmall - 300px}) { // 300px
@content;
}
}
@mixin layout-small-and-up {
@media (min-width: #{$breakpoint-small - 300px}) { // 660px
@content;
}
}
@mixin layout-medium-and-up {
@media (min-width: #{$breakpoint-small - 16px}) { //  944px
@content;
}
}
@mixin layout-large-and-up {
@media (min-width: #{$breakpoint-medium - 16px}) { // 1264px
@content; …
```
=> New responsive classes

src/components/mdTable/mdTable.vue
It happened when I removed one or more rows from the table and clicked on the "select all" checkbox. The number shown was the original data array size, not the new one (after deleting some itens). Example:
```
nutrition = [1,2,3,4,5];
numberOfRows = 5;
nutrition.splice(1,1);
nutrition = [1,3,4,5];
numberOfRows = 5; // this is the bug. it should be 4, not 5.
```
File: mdTable.vue
```
watch: {
data() {
this.numberOfRows = this.data.length;
}
},
```
This will guarantee the numberOfRows is always up to date.
=> Fix MdTable.vue numberOfRows bug

src/components/mdSnackbar/mdSnackbar.scss
This just disables pointer events on the invisible snackbar container so clicks can pass through.
=> Fixes #327. Disable pointer events on snackbar container

src/components/mdSelect/mdSelect.vue
This just removes the null/empty check on `this.selectedText`. If `this.selectedText` is null/empty, we want parent to know so that the label is moved down appropriately.
As far as I can tell removing this check shouldn't break anything.
=> fixes #333 allow null value to be passed to parent

src/components/mdSwitch/mdSwitch.vue
This allows call `$event.preventDefault()` from `<md-switch @change=''`. It is usefull if we want to prevent changing of switch state to confirm change in dialog. Also issue related to this https://github.com/marcosmoura/vue-material/issues/433
Possible use:
```html
<md-switch  @change="$event.preventDefault();start_confirm_dialog()">
```
Or same in `Vue` style:
```html
<md-switch  @change.prevent="start_confirm_dialog()">
```
Also it allows `$event.stopPropagation()` or `@change.stop` which is usefull if md-swith is placed on expanded list and if developer wants to prevent expanding of list when user his on switch.
Solution explained in comments. Thanks
=> Allow preventDefault in md-switch

docs/src/pages/components/Input.vue, src/components/mdInputContainer/mdInputContainer.scss, src/components/mdInputContainer/mdInputContainer.vue
Using `type="search"` presents you with a generic clear button. This adds a button (like "md-has-password") which when clicked, clears the input.
=> Add md-clearable to md-input-container

src/components/mdChips/mdChips.vue
The key 186 is the 'ö' key on german keyboards. I'm sure it means many other things on many other keyboard. So this line would break the component for many people and should be removed.
=> Fix problem with german keyboards.

docs/src/pages/components/Table.vue, src/components/mdTable/mdTable.vue, src/components/mdTable/mdTableHead.vue
Hello,
I realize I did not submit a request for this. But I was in a hurry to get the functionality, and I was happy to dive a little bit in your code.
The purpose of this PR is to manage sorting parameters from outside the table. The use case is for very dynamic tables where the columns, filters, etc are modified by the parent. Re-initializing sort parameters is useful in this context.
=> watchable sort parameters in md-table

docs/src/pages/components/Chips.vue, src/components/mdChips/mdChip.vue, src/components/mdChips/mdChips.scss, src/components/mdChips/mdChips.theme, src/components/mdChips/mdChips.vue
This PR adds a 'md-editable' property  and 'edit' event on md-chip.
They are then used by md-chips to support editing the chips. When a chip is clicked it is removed from the list, and it's content is added to the input where the user can modify it then add it again.
I think it is quite straightforward and integrates nicely with the existing features. I hope you will agree.
On a side note: I wrote my name in the new chip example. I did it because of my lack of imagination, nothing else, feel free to write whatever you want :)
=> md-editable property for md-chip

src/components/mdMenu/mdMenuContent.vue
[bug](http://codepen.io/struwigcd/pen/PWydOK)
issue #478 
``` vue
<div
class="md-menu-content"
@keydown.esc.prevent="close"
@keydown.tab.prevent="close"
@keydown.up.prevent="highlightItem('up')"
@keydown.down.prevent="highlightItem('down')"
@keydown.enter.prevent="fireClick"
@keydown.space.prevent="fireClick"
tabindex="-1">
<md-list>
<slot></slot>
</md-list>
</div>
```
**.prevent** on **@keydown.space.prevent** and **@keydown.enter.prevent** seems to be unnecessary and was preventing the space key on mdInput inside mdMenuContent
=> fixed bug where mdMenuContent was preventing space key on mdInput

src/components/mdTable/mdTablePagination.vue
- Added watchers on mdTotal and mdPage. 
- Changed the binding for the disabled attribute of the next page arrow to use a computed property.
This PR is for the bug described in #482.
=> Fix for issue with md-table-pagination component not enabling the paging buttons when total items is updated, after component is rendered

src/components/mdTable/mdTablePagination.vue
@marcosmoura this is a follow-up of PR #517 to change the name of the computed property for disabling the next-page button; this is to make the code a bit more clear and easy to read. 
I have also changed the `watch` handlers to use the value passed to them instead of referencing the values from the component instance for `mdSize` and `mdPage`.
P.S: I merged your master branch to my fork before raising this PR.
=> Follow-up for #517

docs/src/pages/themes/DynamicThemes.vue
Fixes:
* `it's` (it is) to `its`
* `his theme` to `its theme`
* `a` to `an`
* `have` to `has`
=> Fix grammar and spelling on themes page docs

src/components/mdTable/mdTable.scss
This fixes #534, the icon is now centered inside the md-button when used with md-table
Removing the margin gives back the `margin:auto` set to the `md-icon` class
=> Fix #534 centering icon with md-button in md-table

src/core/components/mdTheme/index.js
Adding a new method `Vue.material.registerPalette` as seen on issue #202 
> https://github.com/marcosmoura/vue-material/issues/202#issuecomment-279143110
> ```js 
> Vue.material.registerPalette( 'my-palette', {
>   50: '#f3e0e0',
>   100: '#e0b3b3',
>   200: '#cc8080',
>   300: '#b84d4d',
>   400: '#a82626',
>   500: '#990000',
>   600: '#910000',
>   700: '#860000',
>   800: '#7c0000',
>   900: '#6b0000',
>   A100: '#ff9a9a',
>   A200: '#ff6767',
>   A400: '#ff3434',
>   A700: '#ff1a1a',
>   darkText: [ 50, 100, 'A100', 'A200' ]
> });
> Vue.material.registerTheme( 'default', { primary: 'my-palette' } );
> ```
=> Added registerPalette method on mdTheme

src/components/mdTable/mdTableHead.vue
Since we are going to rotate the arrow when sort is descending:
```css
.md-table .md-sortable.md-sorted-descending .md-sortable-icon {
transform: translateY(-50%) rotate(180deg);
}
```
The right starting arrow is `arrow_upward`.
=> Fix table arrow sort

src/components/mdRadio/mdRadio.vue
This is a tiny patch helps to address a really strange edge case I discovered testing with PhantomJS.
Take the following instance template:
```
<md-radio v-model="selected"
id="first-option"
class="e2e-first-option"
md-value="1"
name="group-1">
Option One
</md-radio>
```
Under test the following will work as intended in Chrome:
```
vm.$el.querySelector('#e2e-first-option').click()
```
... But the same `click` *does not trigger the handler* as intended in PhantomJS. Instead, you need to use something like:
```
vm.$el.querySelector('.e2e-first-option > .md-radio-container').click()
```
So a workaround exists, but it's pretty unintuitive without digging into the source for the radio component.
=> Adding click handler to mdRadio

docs/src/pages/components/Dialog.vue
Tried one of the code examples and noticed that Vue gave the following warning:
```
[Vue warn]: Missing required prop: "value" 
(found in <MdDialogPrompt>)
```
Added missing argument in code example.
=> DOCS: Added missing argument in code example

src/components/mdTable/mdTablePagination.vue
No matter what value you define as `md-size` option on `md-table-pagination`, it is overridden by the first value in the `md-page-options`.
It was not possible to define pagination options with `[10, 25, 50, 100]` and define the default start size as `25`.
=> Dont overwrite currentSize of mdTablePagination

src/components/mdBottomBar/mdBottomBarItem.vue
Setting to disabled to type Boolean, which fixes the errors reported in #629 :
=> Fixes #629 Unable to set disabled property of md-bottom-bar-item

src/components/mdRadio/mdRadio.scss, src/core/stylesheets/base.scss, src/core/stylesheets/scrollbar.scss
I need to import vue-material's SCSS source files in my private project. I had to add some style declarations AFTER vue-material's styles, but vue-material's styles had hign priority. Maybe this is because of webpack's issue with styles composing (it composes raw CSS files before sass/stylus styles even I add require() for stylus earlier in my code. My vue webpack template found some bugs with SASS variables and extends, so I fixed them.
=> some required scss imports added

src/core/components/mdTheme/dom.js, src/core/components/mdTheme/index.js, src/core/components/mdTheme/mdTheme.vue, src/core/components/mdTheme/mixin.js
This is a first step toward supporting Server-side Rendering (SSR). Several other components still depend on `document` always being available, those will need to be fixed eventually. This PR will at least eliminate the theme engine as a bottleneck.
- Optimize parseStyle method to run a single RegExp replace
- Abstract DOM manipulation to check for VUE_ENV first
- Add theme name to `<md-theme>` element when it would render its own tag
- Recompute styles when a new set of selectors is added (via styles.push)
- Use computed property to find closest themed ancestor for mixin
- Only grab md-name attribute from an md-theme component (`<md-table-edit>` uses the md-name attribute for <input> tags)
=> Refactor Theme Engine

src/components/mdRadio/mdRadio.scss
Related to #634 
Building the `develop` branch and compiling it using `laravel-mix` produces an unfriendly error message in the browser.
`Error: Module build failed: Error`
This fixes it.
=> Fix undefined variable in md-radio SCSS

src/components/mdTable/mdTablePagination.vue
Subtotal on pagination is not updating when mdTotal value is updated (e.g. pagination data fetched from AJAX). This fixes it.
=> Fix subtotal not updating

docs/src/pages/components/Select.vue, src/components/mdSelect/mdOption.vue, src/components/mdSelect/mdSelect.vue
Fix on issue #742 
Once the user changed the `v-model` from `mdSelect` asynchronously, the `mdCheckbox` from the `mdOptions` did not selected the elements provided via the `v-model`. See: [Codepen](http://codepen.io/dEradicated/pen/qRJapb) 
I created a function that, once the `v-model` from `mdSelect` changes, it filters the `mdOptions` and check the `mdCheckbox` to true.
The solved issue can be seen below. The gif shows both options and selections being made asynchronously.
=> fix on issue #742 - v-model reflects changes on mdSelect

src/components/mdCheckbox/mdCheckbox.vue, src/components/mdChips/mdChips.vue, src/components/mdRadio/mdRadio.scss, src/components/mdSelect/mdSelect.vue
- Allow md-checkbox to be toggled by clicking the label
- Add capability to edit chips in md-chips
- Fix error in md-select when not used with md-multiple
=> Bunch of fixes

src/components/mdTabs/mdTabs.scss
I'm opening this PR to start working on the performance issues raised in #654. The issues identified are:
I don't have much experience digging into rendering performance on web pages, but so far I've removed the `width:9999em` property from `.md-tabs-wrapper` and that seems to have made a significant performance improvement (measured with the FPS tool in chrome, and simply visually). I can see no visual difference to the tab's appearance or animation in Safari, Chrome, Firefox (latest versions of each, Mac OS and Ubuntu 16.04.) It's simply smoother.
@marcosmoura: Can you give some history to why such a huge width was required, when you're already setting it to be absolutely positioned?
@pablohpsilva, @sandhose: If the two of you would like to help with testing, that'd be great. I'd love …
=> WIP: Performance Improvements

src/components/mdTabs/mdTabs.scss
- Fix tab headers not properly flexed in md-fixed
- Fix tab headers not centered in md-centered
=> md-tabs fixes

docs/src/pages/components/Icon.vue
one of icon font examples got missing icons due mixed content issues
=> Update Icon.vue documentation page

src/components/mdCard/mdCard.theme, src/components/mdCard/mdCardMedia.vue, src/components/mdCheckbox/mdCheckbox.scss, src/components/mdRadio/mdRadio.scss, src/components/mdRadio/mdRadio.vue, src/components/mdTable/mdTableRow.vue
- Fix md-icon-button not white on md-card-media-cover
- Allow custom md-ratio
- Fix cursor being a pointer when md-checkbox/md-radio is disabled
- Allow md-radio to be toggled even if id/name is not set
- Fix select all checkbox not updating when all md-table-row's are selected
=> Small fixes

src/components/mdInputContainer/mdInputContainer.theme, src/components/mdTable/mdTableHead.vue, src/components/mdTabs/mdTab.vue, src/components/mdTabs/mdTabs.vue
- Fix lingering white border on `md-input-container` buttons (`md-has-password`/`md-clearable`)
- Fix `md-table` sort type not defaulting to 'asc' when `md-sort` prop is set
- Add `md-iconset` support to md-tab (fixes #704)
=> Small enhancements

src/components/mdChips/mdChips.vue, src/components/mdInputContainer/mdInputContainer.vue, src/components/mdTable/mdTablePagination.vue
Removed mdInputContainer clear/password button tabindex for better tab navigation in forms.
Debounce = 0 on mdChips input allows user to fastly type and add/remove chip (currently, the user has to wait or press enter repeatedly to add chip, since there is a verification for empty "currentChip" model value). Also, the user could remove a chip even with text on input due to the default debounce.
=> Small fixes on mdChips, mdTablePagination (issue #830) and mdInputContainer buttons

src/components/mdTabs/mdTabs.vue
use keep-alive on the route containing the md-tabs
navigate from the component containing the md-tabs to another component, change the viewport size (resize your browser) and go back
Tested using the following setup (versions come from the package.json on my project)
* Vue - ^2.2.2
* Vue Router - ^2.2.0
* Vue Material - ^0.7.1
* Browsers: All of them, from desktop to mobile
To show the tabs as they were before
When the size of the viewport changes and the component is not active, the computed property 'width' on the MdTab component is set to 0px. The keep-alive caches the component, so when it's brought back to the 'width' remains 0px
https://codepen.io/brunocalou/pen/Mmeyzd
=> Fixed disappearing tabs when the component is kept alive and the viewport is resized

src/core/components/mdTheme/index.js
The bug was submitted by myself and today I found some time to investigate the issue.
It seems there were two issues at hand. One was that the default theme class wasn't being set at all because the default class was already being set as an active class and with the refactored code you cannot set the already set theme. 
So I changed the default set theme in data object to be explicitly null and I'm setting a default theme on created event.
The other issue was that the custom theme wasn't being set, but it turned out it was being set, but the body class wasn't being applied. The reason was that the call to the function to set the body class had wrong parameter order. So I fixed the ordering and it's working correctly now.
=> Theming fix - bug #849

src/components/mdInputContainer/common.js
Fixes logaretm/vee-validate#588 seriously this time. :D
=> Pass value as first parameter on blur/focus events in md-input

src/components/mdList/mdListItemExpand.vue
Padding calculation should include `.md-list-expand` alone, not the whole parent `md-list-item`.
Try the fix with the following template:
```pug
<template lang="pug">
md-list-item
.md-list-text-container
span Line 1
span Line 2
span Line 3
span Make sure the parent `.md-list-text-container` is high enough
span And the div will be cropped if this patch haven't been applied
md-list-expand
md-list
md-list-item.md-inset
p foo
md-list-item.md-inset
p foo
</template>
```
May related to #686.
Signed-off-by: Wenxuan Zhao <viz@linux.com>
=> Fix incorrect padding for md-list-expand.

src/components/mdTable/mdTablePagination.vue
#841 stated that the pagination on `mdTablePagination` did not work. I narrowed it down that the component is not initialized correctly. If I navigated away and back to the page again the pagination worked. I included a line in the `$nextTick` function to compute the totalItems.
=> Fix Pagination in 0.7.2+

src/components/mdSnackbar/mdSnackbar.vue
When trying to show a snackbar when it's already shown,it was staying open or in some cases it disappeared, never to appear again. And trying to do a close and then open programmatically, it would always fail and would just hide the snackbar.
This adds a functionality that would hide the previous snackbar and open a new one, when you open a new one while the previous is still open.
=> Close snackbar before opening a new one - #926

src/core/stylesheets/mixins.scss
Quick fix for issue with combinations of md-hide-{size n} / md-hide-{size n+1}-and-up, where both elements are hidden at the same time.
This occurs when the screen width matches the exact breakpoint.
https://codepen.io/Madsn/pen/jLbeEZ for samples
Related to #631 - or possibly closes it as an issue, though there is some discussion on an enhancement to the layouts going on.
=> Both elements hidden when using hide-{size}-and-up / hide-{size-1}

src/components/mdTabs/mdTab.vue, src/components/mdTabs/mdTabs.vue
This will allow for custom SVG/PNG icons to be used in `md-tab`. The icon source can be specified with the `md-icon-src` attribute and uses the existing `md-src` attribute in `md-tab`. I renamed it to `md-icon-src` so that it is obvious that it is an icon source and not anything else.
Example:
```
<md-tabs>
<md-tab md-icon-src="/icons/icon.svg"></md-tab>
</md-tabs>
```
Works well with labels too.
=> Added support for custom icons in md-tab with md-icon-src attribute

src/components/mdRadio/mdRadio.vue
From what i think i understood, when clicking on a radio´s label the event is tied to the input itself and therefore bubbles up to the radio container, triggering the change event twice on the way.
This is, imo, undesired behaviour.
Adding ```.prevent``` on the event handler of the label (like in the checkbox component) will prevent default behaviour of tying to input and therefore only trigger change once.
https://vuejs.org/v2/guide/events.html#Event-Modifiers
fixes #953
=> A really simple fix for avoiding double `change` trigger when clicking on md-radio's label

src/components/mdTabs/mdTabs.vue, src/components/mdTooltip/mdTooltip.scss
This fixes the `header-item` slot functionality in mdTabs as stated in the documentation. This was initially implemented in PR #596 but was removed in commit 500e5b5 (possibly merging an older branch).
I had to make a separate PR after my previous one as I had to move the element for `md-icon-src` functionality to be in `header-item`, if not there would be merging issues.
This PR also fixes tooltips on mdTab by making the `md-tooltip` element a child of the `tab-header` button element and not `md-tab-header-container`.
And finally, I also fixed a very slight shift in tooltip text as it moves. Here's an example of how this looks like:
*The text moves a little.*
And here's an example of letter-spacing being applied to `md-tooltip` (after fix):
*There is no longer any shift in the text.* …
=> Fix header-item templating (issue #896) and tooltips on mdTab

.github/CONTRIBUTING.md
This is to specifically state for contributors to make changes to their `develop` (or `develop`-derived) branch and not `master`.
(See #956)
=> State that contributors should work in the develop branch (modify CONTRIBUTING.md)

docs/src/pages/components/Input.vue, src/components/mdInputContainer/mdAutocomplete.vue, src/components/mdTable/mdTablePagination.vue, src/core/utils/autocomplete-common.js
- Fixed lost focus on input when the menu appeared with the results
- Added max-res prop which can be added to limit the number of results shown in the list
- Show dropdown menu when input receives focus (not just when typing)
- Added a possibility to set max-chars to 0 and show the list (not fetched, but list) immediately on input focus, with input being empty.
- Fix mdTablePagination.vue error because of which it did not compile (linter issue with unused var)
- Added max-res in the docs
=> Fixed an issue with md-autocomplete and added some additional functionality to it

docs/src/pages/components/Input.vue
Update the example "Regular fields" in the component `md-input` where the wrong component were used.
=> The autocomplete component should be a md-autocomplete and not a md-input.

src/components/mdTable/mdTablePagination.vue
hide the pagination label and assign currentSize as mdSize while mdPageOptions is false.
The issue:
Fixed:
=> Fix issues while mdPageOptions is false

docs/src/pages/components/File.vue
Changing the mis-typed word 'devide' to be correct 'device'
=> Fix typo on file upload documentation

src/components/mdList/mdListItemExpand.vue, src/components/mdMenu/mdMenu.vue, src/components/mdOnboarding/mdBoards.vue, src/components/mdStepper/mdStepper.vue, src/components/mdTabs/mdTabs.vue
Several of the components (mdTabs, mdBoards, mdMenu, mdStepper, mdListItemExpand) use requestAnimationFrame to monitor scroll position and other attributes of their DOM element.  Since it's possible for a Vue component (and associated elements) to be destroyed before the rAF callback is executed, we set a guard in beforeDestroyed (`this._destroyed = true;`) and abort the callback if it's set.
=> calls to requestAnimationFrame must check if component has been destroyed

src/components/mdTabs/mdTabs.vue
It would cause error with disabled first tab because tabs active the first tab while there was no tab active yet.
```
[Vue warn]: Error in mounted hook: "TypeError: Cannot read property 'icon' of undefined"
found in
---> <MdTab>
<MdTabs>
<Root>
warn @ vue.js:440
handleError @ vue.js:525
callHook @ vue.js:2562
insert @ vue.js:3381
invokeInsertHook @ vue.js:5205
patch @ vue.js:5370
Vue._update @ vue.js:2327
updateComponent @ vue.js:2443
get @ vue.js:2780
run @ vue.js:2850
flushSchedulerQueue @ vue.js:2619
(anonymous) @ vue.js:661
nextTickHandler @ vue.js:608
Async Call
timerFunc @ vue.js:623
queueNextTick @ vue.js:671
queueWatcher @ vue.js:2706
update @ vue.js:2840
notify @ vue.js:738
reactiveSetter @ vue.js:968
proxySetter @ vue.js:2965
goA @ yPkJjGJKqbbk:80
boundFn @ vue.js:170
click @ …
```
=> fix disabled first tab cause error

.npmignore, package.json, yarn.lock
You already mention in the readme that you want vue-material to be standalone and therefore bundle vue with it.
Would it be feasible to trust vue to not release breaking changes in minor/hotfix-updates? If so, I would be glad to have this merged to save some bandwidth and processing power with avoiding bundling two versions of vue.
I understand the notion of locking the version you're running internally, so if you discard this PR, no feelings will be hurt.
=> Update and fix dependencies

docs/src/pages/components/Stepper.vue, src/components/mdStepper/mdStep.vue, src/components/mdStepper/mdStepHeader.vue, src/components/mdStepper/mdStepper.scss, src/components/mdStepper/mdStepper.theme, src/components/mdStepper/mdStepper.vue
Hi @pablohpsilva, 
I think that I have found a solution for fixing the clickable header (in #968).
In addition to that, I compared the Material.io again and saw that vue-material doesn't support errors in the step.
So tried to fix that (with an md-error prop in the stepper) but I would not mind if you throw it away :P 
I'm still learning code so I hope you like it.
=> Fix clickable [mdStepper] header and added md-error

src/components/mdButtonToggle/mdButtonToggle.vue
Adds option to disable click based toggling of the md-toggle class. Disabled by default.
This allows you to have the md-toggle class just depend upon your data, so that when you update the data the appropriate toggle button(s) will show as highlighted.
This is a small change if you ignore whitespace: https://github.com/vuematerial/vue-material/pull/1001/files?w=1
=> Adds option to disable click based toggling

docs/src/pages/components/ButtonToggle.vue, src/components/mdButtonToggle/mdButtonToggle.scss, src/components/mdButtonToggle/mdButtonToggle.theme
Enables adding an "md-raised" class to "md-button-toggles" with
`<md-button-toggle class="md-raised md-primary">`
screenshot (see last line: "works with text too")
I find it clearer to see the buttons, and it's opt in, so I don't think there's much downside.
Thanks for your work on this library btw!
=> Enables md-raised class on md-button-toggle

src/components/mdSelect/mdSelect.vue
Fix mdSelect 'opened' and 'closed' events.
Issue: #1007 [md-select] opened and closed event never fired
=> [mdSelect] Fix issue #1007

docs/src/pages/themes/Configuration.vue
Default background color changed to `white` in [6a95f146eab141854c4159e1d69db564a59925ea](https://github.com/vuematerial/vue-material/commit/6a95f146eab141854c4159e1d69db564a59925ea#diff-62683009a7aba744dbb751b3bd6e9873R9) after v0.7.1
=> fix default background color in documentation

src/components/mdTable/mdTable.scss
`md-checkbox` components inside of `md-table` components are a little stretched due to the `min-width` applied [here](https://github.com/vuematerial/vue-material/blob/578c4aa7a0bed3dc60f24b48586d29bbe3168169/src/components/mdCheckbox/mdCheckbox.scss#L22) overriding the sizing applied [here](https://github.com/vuematerial/vue-material/blob/master/src/components/mdTable/mdTable.scss#L229):
Before PR (checkboxes are stretched):
After PR (checkboxes are square):
=> Fixes md-checkbox-container sizing in md-table component

src/components/mdOnboarding/mdBoards.theme
Using `active` instead of `focus` to avoid the clicked dot still highlight after page changed.
Issue: #1095
=> [mdOnboarding] Fix #1095

src/components/mdInputContainer/mdAutocomplete.vue
per https://github.com/vuematerial/vue-material/issues/1059
tested and working for me.
also note, i tried putting the assignment in the `nextTick` call, but this caused the value to populate only after focusing the element...
=> [mdAutocomplete] set the query value (for the inner mdInput) on mount

src/components/mdTooltip/mdTooltip.vue
The error occurs because, on this specific scenario, the following happens:
1 - `mounted` hook is called
2 - `beforeDestroy` hook is called
3 - `removeTooltips` is called inside the `beforeDestroy` hook
4 - `tooltipElement` is undefined, because it was never assigned ---> error
5 - `$nextTick` is called and assigns `tooltipElement` to `$el`
This is fixed by checking if `tooltipElement` is already defined
=> Checked if tooltipElement is undefined before accessing it on removeTooltips function #1066

src/components/mdButton/mdButton.scss, src/components/mdTable/mdTable.scss
Button icon should be able to be set color via `.md-raised`, `.md-primary`, `.md-accent`, `:disabled` instead of always `rgba(#000, .54)`.
Tested Cases:
`icon`, `button`, `button:disabled`, `button.raised`, `button.primary`, `button.raised.primary`, `button.raised.primary:disabled`
- Toolbar
- Toolbar - before:
- Toolbar - after:
- Table
- Table - before:
- Table - after:
=> [mbButton] Fix button icon color

src/components/MdTable/MdTable.vue
Related to #1146
fix #1146
After table values changed, the `MdTable.hasValue` was not updated.
* Adding a watcher to make `MdTable.hasValue` follow the computed `hasValue`.
* Declaring all `MdTable` properties in `data()` instead of some declarations in `provide()`.
=> fix(MdTable): fix MdTable.hasValue not synced issue

src/components/MdChips/MdChips.vue
Changes:
* Changing `inputValue` default value as `''`.
* Removing [unnecessary plus symbol](https://github.com/vuematerial/vue-material/blob/7fdd318d9ebcf13e6c7d9a2e6a7de205f6918d53/src/components/MdChips/MdChips.vue#L69).
Notice that this commit need to be reverted if `mdLimit` allow `String` in the future.
* Empty chip could not be inserted anymore.
* Changing `modelRespectLimit` from `methods` to `computed`.
* The input would be removed while reaching limit.
=> fix(MdChips):  fix issues

docs/app/pages/Components/Datepicker/examples/CancelOpenDatepicker.vue
=> docs(Datepicker): Using client timezone instead of UTC to avoid misunderstanding

README.md
Today, I wanted help for vue-material...
I see the slack channel but I can't find the slack invitation link.
I must search in issue list. Maybe we can add it on the README?
=> doc(README.md): Add slack invitation link

src/components/MdField/MdInput/MdInput.vue
Related to #1170 .
* fix password toggle
* add computed `isPassword`
* reset toggle password state while type changed    
Steps: toggle password to visible -> switch type to text -> switch type to password
before: the toggle is not resetted but the input is password type.
after: the toggle will reset
=>  fix(MdInput): fix password toggle

docs/app/components/CodepenEdit.vue
`undefined` would be inserted into the style block in codepen if there is no `<style>` in the example.
Passing an empty string into it instead of `undefined`.
=> docs(Codepen): Fix codepen style undefined

src/components/MdField/MdTextarea/MdTextarea.vue
=> fix(MdTextarea): prevent emitting `inputEvent` object on `input`

src/components/MdApp/MdApp.vue
Make custom classes and style allowed in `MdApp`.
Example:
```html
<md-app :class="appClass" style="height: 100vh;">
<md-app-toolbar class="md-primary">
<span class="md-title">My Title</span>
</md-app-toolbar>
<md-app>
```
fix #1222, #1250.
Related to #1254 .
=> feat(MdApp): custom class and style

src/components/MdMenu/MdMenu.vue, src/components/MdMenu/MdMenuContent.vue
Remove [`stopPropagation` from `MdMenu`](https://github.com/vuematerial/vue-material/blob/90733136b2dd6a3d166848f20ad266b7114bef38/src/components/MdMenu/MdMenu.vue#L108) to trigger [close-menu click observer](https://github.com/vuematerial/vue-material/blob/90733136b2dd6a3d166848f20ad266b7114bef38/src/components/MdMenu/MdMenuContent.vue#L188).
fix #1255
=> fix(MdMenu): Close menu while another is opened

docs/app/template/MainNav.vue, src/components/MdButton/MdButton.vue, src/components/MdCard/base.scss, src/components/MdField/MdSelect/MdSelect.vue
Components issues: #1157, #1190, #1149
And docs issue #1134
=> fix: z-index issues

docs/app/pages/Components/Datepicker/Datepicker.vue, src/components/MdDatepicker/MdDatepicker.vue
close https://github.com/vuematerial/vue-material/issues/1267, https://github.com/vuematerial/vue-material/issues/1260
=> feat(MdDatepicker): override browser native pickers

src/components/MdMenu/MdMenuContent.vue
check whether clicked target is contained in menu content element within `bodyClickObserver`
I found that `this.$el` is always `` [here](https://github.com/vuematerial/vue-material/blob/9f61c0b1e0bf6940de1a1e87fedc52c6c0882c6b/src/components/MdMenu/MdMenuContent.vue#L191). Add a statement [`isMenuContentEl`](https://github.com/vuematerial/vue-material/commit/f3fd5b6584c8687c521de58a5064e8d686d0592c#diff-7ff54ca9681d4b418d0a582326ecff70R192) to prevent menu closing from `bodyClickObserver`.
`MdMenu`, `MdSelect`, `MdAutocomplete` tested.
Note that `md-close-on-select` only fire `close` event fired while there are one or more [interaction events](https://github.com/vuematerial/vue-material/blob/9f61c0b1e0bf6940de1a1e87fedc52c6c0882c6b/src/core/utils/MdInteractionEvents.js) bound on …
=> fix(MdMenu): fix close-on-select props

docs/app/pages/Components/Chips/Chips.vue, docs/app/pages/Components/Chips/examples/DuplicatedFeedback.vue, src/components/MdChips/MdChip.vue, src/components/MdChips/MdChips.vue, src/components/MdChips/theme.scss
* New props `md-always-check-duplicated` would check if there is duplicated chip on input value change if set it as `true`.
* Class `md-duplicated` would be added on the duplicated chip while it was detected.
* Class `md-duplicated` has the same style with `md-accent` as default.
* You could customize `md-duplicated` style via `deep selector` if you are using scoped CSS.
fix #1212
=> feat(MdChips): feedback for duplicated chip

yarn.lock
upgrade `vue-template-compiler` in yarn.lock to resolve vue packages version mismatch.
`vue` is not in `yarn.lock` and it's released `v2.5.10` yesterday.
`vue-template-compiler` was `v2.5.9` in `yarn.lock`
That cause error that says `vue packages version mismatch`
=> fix: upgrade yarn.lock

src/components/MdLayout/layout.scss, src/components/MdLayout/variables.scss
I want to suggest these changes to be able to use the responsive md-layout also on large and extra large screens. Should fix #1242
=> Adding xlarge and large variables to the layout component

src/components/MdList/MdListItem/MdListItemLink.vue
`<a>` attributes `download`, `hreflang`, `ping`, `rel`, `type` supported
reference: [`<a>` - HTML | MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a)
fix #1320
=> feat(MdListItemLink): all `<a>` attributes supported

src/components/MdField/MdInput/MdInput.vue, src/components/MdField/MdTextarea/MdTextarea.vue
Fixes #1261.
Notes: use `Object.assign` to deep copy `this.$listeners`. `delete` `input` key as opposed to setting to `undefined` which causes error.
=> (Fix #1261) Don't emit input directly in MdInput and MdTextarea

src/components/MdField/MdTextarea/MdTextarea.vue
add `onInput` as `input` to listeners
fix #1340
=> fix(MdTextarea): fix input event handler

src/components/MdHighlightText/MdHighlightText.vue
=> fix(MdHighlightText): avoid print `'null'`

build/loaders/component-example-loader.js
Using babel to compile javascript in examples
`Promise`(with 1eb3ee7786619ce0b04fbfdff39f9bf7e903f9de), `async` / `await` with IE 11.125.16299.0 in windows 10 via VirtualBox tested.
fix #1337
=> docs(componentExampleLoader): replace vue es2015 compiler with babel

docs/app/pages/Components/Table/examples/TableSingle.vue, src/components/MdTable/MdTable.vue, src/components/MdTable/MdTableHeadSelection.vue, src/components/MdTable/MdTableRow.vue, src/components/MdTable/MdTableRowGhost.vue
BREAKING CHANGE: no more `md-selected` event from `MdTableRow` because of too many duplicated events on a selection. It should be emitted only from `MdTable` both in `single` and `multiple` selecting mode. It was emitted from `MdTableRow` in `single` and from `MdTable` in `multiple` before.
new props `:md-selected-value.sync` for reactive selection.
```vue
<md-table v-model="people" md-card md-sort="name" :md-selected-value.sync="selected" @md-selected="onSelected">
```
Notice that disabled row could be selected from `:md-selected-value`.
fix #1292
`MdTable.selectedItems`, `MdTable.selectable` change type to array for easier selection controlling.
Selection is determined by instance comparing now.
It was determined by comparing ids in single selection mode and comparing indexes in …
=>  feat(MdTable): reactive selection

src/components/MdTable/MdTableCell.vue
compute `MdTable.items` again on column remove.
fix #1347
=> fix(MdTable): remove table head while column removed

docs/app/pages/Components/Menu/Menu.vue
* change component name to avoid warning
`[Vue warn]: Do not use built-in or reserved HTML elements as component id: Menu
`
* correct `md-direction` API
=> docs(Menu): fix warnings

src/components/MdMenu/MdMenuContent.vue, src/components/MdPopover/MdPopover.vue, src/components/MdPortal/MdPortal.js
dom constructors do not have name property in IE.
Replace that with comparing by their [node type](https://developer.mozilla.org/en-US/docs/Web/API/Node/nodeType).
Tested with chrome and IE(with #1342), both got `1` stand for normal element and got `8` for comment.
~~Related to #1263~~
~~There is another bug with #1263 that [`menuHeight`](https://github.com/vuematerial/vue-material/blob/0c1c9576fad8584b44a8a5b4ac2eb22e7f034b52/src/components/MdField/MdSelect/MdSelect.vue#L137) is always `0` therefore menu still not works in IE with this change yet.~~
update: fix height with 24d927c3ffd39029027e0c1f9634db4ef6b5c6ab, similar to #1356
fix #1263
IE11 & edge in Win10(VirtualBox), firefox & chrome in Xubuntu tested.
`MdMenu`, `MdSelect`, `MdAutocomplete` tested.
=> fix: node type statement(menu compatibility with IE)

src/components/MdField/MdSelect/MdSelect.vue, src/components/MdMenu/MdMenuContent.vue
Remove `uuid` from `MdMenuContent` and `MdSelect` and use `ref` instead of `uuid` to get menu contain container.
Field would be focused on the menu entered. I think it's better than the `setTimeout` way.
=>  refactor(MdSelect): remove uuid

src/components/MdTable/MdTable.vue
Fixed table needs to have `max-height` for content of table to allow scrollbar in Firefox
=> fix(MdTable): fix height of fixed table for firefox

src/components/MdField/MdFieldMixin.js, src/components/MdField/MdInput/MdInput.test.js
I've created a codepen which demonstrates an issue: https://codepen.io/jastkand/pen/EoQGKV
You can open a devtools and see that there are `name` attributes on `input` and `textarea`. When you try to change any input the `name` attribute will be removed which is not an expected behavior.
This also should fix this issue https://github.com/vuematerial/vue-material/issues/1278, because serialization uses `name` attributes
=> fix(MdFieldMixin) Preserve the name attribute on change

docs/app/pages/Components/Chips/Chips.vue, docs/app/pages/Components/Chips/examples/Format.vue, src/components/MdChips/MdChips.vue
New props `:md-format` for the formatter before chip insertion. Effects to insertion and duplicated-checking.
fix #1288
=> feat(MdChips): formatter

docs/app/pages/Components/Drawer/Drawer.vue
I'm not sure, but I think these should be `md-persistent=` and not `md-permanent=`. These are the two last props in this [page](https://vuematerial.io/components/drawer).
=> Docs: Wrong props

src/components/MdAutocomplete/MdAutocomplete.vue
=> fix(MdAutocomplete): prevent show options twice

src/components/MdRipple/MdRipple.vue, src/core/utils/MdDebounce.js
=> feat(MdRipple): multiple waves

src/components/MdDatepicker/MdDatepicker.vue, src/components/MdDatepicker/MdDatepickerDialog.vue
=> feat(MdDatepicker): emit date without confirming

src/components/MdTabs/MdTabs.vue
`setIndicatorStyles` on `transitionend` for correct position while alignment changed
fix #1432
=> fix(MdTabs): correct indicator position while alignment changed

src/components/MdField/MdSelect/MdSelect.vue
Make options reactive via a hidden node.
It might not the best solution but it works.
Notice that if you want to update the selected value with new options, await next tick for the `MdSelect.items` updated.
fix #1262
fix #1389
=> fix(MdSelect): Reactive options

src/components/MdTabs/MdTabs.vue
``right: `calc(100% - ${buttonWidth + buttonLeft}px)` `` work weird with safari, replace it with `width` way to set indicator position
fix #1304
=> fix(MdTabs): fix indicator

src/components/MdTooltip/MdTooltip.vue
`mdActive` was never updated to `true` via `.sync` before
=> fix(MdTooltip): update `mdAcitve` while `shouldRender` is `true`

src/components/MdTabs/MdTabs.vue
I tested the case https://github.com/vuematerial/vue-material/issues/1432#issue-291045326 I got `min-width` as the last property on transition end, so I `setIndicatorStyles` while that transition end.
https://github.com/vuematerial/vue-material/blob/3e69486a3003c547dfc8ae5220570d9b3d9ad94a/src/components/MdTabs/MdTabs.vue#L124
In this case https://github.com/vuematerial/vue-material/issues/1432#issuecomment-362102707, I got `flex-grow` as the last transition end.
We never know which property is the last transition end, so I think it's better to `setIndicatorStyles` on every `transitionend`.
I tried to use [`transitionstart`](https://developer.mozilla.org/en-US/docs/Web/Events/transitionstart) to implement a counter for checking which property is on the last transition end, but that is an …
=> fix(MdTabs): correct indicator position on transition end

src/components/MdList/MdListItem/MdListItem.vue, src/components/MdMenu/MdMenuItem.vue
* bind close event if menu item is an `a` element
* always show `MdListItemButton` instead of `MdListItemRouter` or `MdListItemLink` if `disabled` is `true` to disable the menu list item, or there would be a enable item with disabled style.
* remove useless variable `hasInteraction`
fix #1471
=> fix(MdMenuItem): fix router

src/components/MdTable/MdTableRow.vue, src/components/MdTable/MdTableRowGhost.vue
MdTable was working with a 2D array as a data source (the data for each row is an array instead of an object), now there is a warning for each row:
[Vue warn]: Invalid prop: type check failed for prop "mdItem". Expected Object, got Array.
=> Allow 2D array as the model of MdTable

src/components/MdField/MdSelect/MdSelect.vue
`setFieldContent` if options are changed.
with this, we don't need to wait for the next tick after options be updated to change the `v-model` of `MdSelect` anymore. `MdSelect` will always check the options and update the text while options are updated.
fix #1389
https://github.com/vuematerial/vue-material/issues/1389#issuecomment-363326766
=> fix(MdSelect): setFieldContent on updated

src/components/MdList/MdListItem/MdListItemExpand.vue
new event `@md-expanded`, `@md-collapsed`
The original issue could works with this:
```vue
<md-list-item md-expand v-for="video in data" :key="video.Id" :md-expanded.sync="expand[video.Id]" @md-expanded="toggle(video.Id)">
```
fix #1490
=> feat(MdListItemExpand): expanded and collapsed events

src/components/MdRipple/MdRipple.vue, src/components/MdRipple/MdWave.vue, src/components/MdRipple/index.js
* clear wave immediately instead of debounce delay.
* `<transition group>` make `MutationObserver` callback many times by one click, and it will cause page dead with CPU leakage.
This could reproduce with this reproduction: https://github.com/vuematerial/vue-material/issues/1500#issuecomment-364850236 with `1.0.0-beta-8`.
I can't find a way to configure the `<transition group>` to work as fine as `<transition>`. The solution for now is using `<transition>` and make waves act like old single ripple with `animating`.
related to #1419, #1500
=> fix(MdRipple): clear immediately

docs/app/pages/Components/Menu/Menu.vue
The `md-opened` and `md-closed` events have been added to the api section of `md-menu` #1517
=> [MdMenu]:Updated documentation with events in api section

src/components/MdBottomBar/MdBottomBarItem.vue
Fix missing props `to` for vue router link after `$attrs` changed.
`$attrs` is read only, so I think replace it with a new computed `attrs` is better.
Notice that the props `to` would be always sent via props, therefore there will be no html attribute `to` on `<a>` anymore.
fix #1412
My test case:
```vue
<template>
<div>
<md-checkbox v-model="funcPresent">test</md-checkbox>
<md-bottom-bar md-type="shift" class="md-layout md-alignment-center-center md-primary" md-sync-route>
<md-bottom-bar-item to="/components/bottom-bar/123" md-icon="home" md-label="Home" class="md-layout-item">
</md-bottom-bar-item>
<md-bottom-bar-item v-if="funcPresent" to="/components/bottom-bar/func" md-icon="lightbulb_outline" md-label="Func" class="md-layout-item"> </md-bottom-bar-item>
</md-bottom-bar>
</div> …
```
=> fix(MdBottomBarItem): missing props to for router link

src/components/MdButton/MdButton.vue, src/components/MdButton/MdButtonContent.vue, src/components/MdRipple/MdRipple.vue
* new props `md-event-trigger` for `MdRipple` to disable event listener.
* Use method call instead of event trigger to make ripple work with firefox because event could not be triggered on element in button with firefox.
* cancel `touchstart`, `touchmove`, `touchend`, `mousedown`, `mouseup` `stopPropagation` to make button listeners works.
fix #1461
=> fix(MdButton): Ripple for firefox

src/components/MdCheckbox/MdCheckboxMixin.js
Add object & array to possible checkbox values.
Don't see reason why not to?
These is giving errors now when trying to migrate to vue-materials from current implementation
=> Add object to possible checkbox value

src/components/MdTabs/MdTabs.vue
Fix #1513 
Maybe it can resolve #1500 ?
=> fix(MdTabs): remove ResizeObserver

docs/app/pages/Components/Menu/Menu.vue, src/components/MdMenu/MdMenuContent.vue
This PR is a possible fix for issue #1206.
This issue might be related to Popper.js library.
After render, `popper` instance which wraps `MdMenuContent` is mounted as a direct child of `body`, and changes in `body`'s position affects where the popper is mounted.
By adjusting `popperSettings.modifiers.offset` with `body`'s position relative to the viewport, the menu will be correctly positioned.
```css
body {
margin-top: 100px;
margin-left: 100px;
}
/* Or an element which can affect body's position */
#app {
margin-top: 100px;
margin-left: 100px;
}
```
Menu is off position the size of the `body`'s `margin` (or any elements pushing the `body`s position).
Really appreciate for feedbacks and reviews.
=> [MdSelect] Adjust position when body has margin

src/components/MdButton/MdButton.vue
Button events `touchstart`, `touchmove`, `mousedown` should be triggered when `rippleWorks` is `false`.
=> fix(MdButton): fix events

src/components/MdTable/MdTable.vue
=> feat(MdTable): allow custom value for mdHeight

build/lib/webpack.js
put `BannerPlugin` after `UglifyJsPlugin` to make banner comment appear in `.min.js`
Notice that all `.js` in `dist/components` will start with banner too.
fix #1516
=> build: banner comment for .min.js

src/components/MdTable/MdTable.vue
=> fix(MdTable): emit selected / update event only when selected item(s) really changed

src/components/MdField/MdSelect/MdSelect.vue
=> fix(MdSelect): pass props `id`, `name` as attributes

docs/app/pages/Components/Datepicker/Datepicker.vue, src/components/MdDatepicker/MdDatepicker.vue
=> feat(MdDatepicker): add close, open events

docs/app/pages/Components/Dialog/Dialog.vue, src/components/MdDialog/MdDialog.vue
There might be cases where user wants to know if clicked outside of dialog (at least I have use cases)
=> comp(MdDialog): Add emit event when clicked outside of dialog

src/theme/mixins.scss
http://sass-lang.com/documentation/file.SASS_CHANGELOG.html#3_5_0__12_July_2017_
> The way CSS variables are handled has changed to better correspond to the CSS spec. They no longer allow arbitrary SassScript in their values; instead, almost all text in the property values will be passed through unchanged to CSS. The only exception is #{}, which will inject a SassScript value as before.
fix #1619
=> fix(mixins.scss): inject SassScript value to CSS variables to fix libsass 3.5.0

src/components/MdTable/MdTableRow.vue
When table is empty, `MdTable.hasValue` is `false`. This made that removed items keep in `MdTable.selectable`.
fix #1610
=> fix(MdTableRow): removeSelectableItem when empty

src/components/MdTabs/MdTabs.vue
This reverts commit b33d0d6a8c59f4c8d310276284d34fa36746d10f.
Seems Safari fix this bug.
Safari Version 11.0.3 (13604.5.6) tested.
=> Revert "fix(MdTabs): fix indicator (#1448)"

docs/app/pages/Components/Datepicker/Datepicker.vue, docs/app/pages/Components/Datepicker/examples/CloseOnSelectDatepicker.vue, src/components/MdDatepicker/MdDatepicker.vue, src/components/MdDatepicker/MdDatepickerDialog.vue
Click to select date without confirm and close the dialog immediately.
* If disable `MdImmediately`, date would not be selected before click `confirm` button. Before this change, `confirm` button is useless.
* Selected date in datepicker will reset when `cancel` button clicked(on the dialog closed).
* `setContentStyles` is always called when transition start. I think this way is better than `setTimeout`.
* fix clear button did not clear `selectedDate` bug.
fix #1606
=> feat(MdDatepicker): add immediately option

docs/app/pages/Components/Checkbox/Checkbox.vue, docs/app/pages/Components/Checkbox/examples/RegularCheckboxes.vue, src/components/MdCheckbox/MdCheckbox.vue, src/components/MdCheckbox/MdCheckboxMixin.js, src/components/MdCheckbox/theme.scss
=> feat(MdCheckbox): add `indeterminate` look, prop

src/components/MdDialog/MdDialogConfirm/MdDialogConfirm.vue
As recommended in #1622.
Two things I came across:
1. I tried running `npm run build`, but it changed just about every file in the `dist` directory, so I didn't commit it.
2. In your [contributing guide](https://github.com/vuematerial/vue-material/blob/master/.github/CONTRIBUTING.md#development-setup), you tell people to run `npm install`, however I noticed you have a `yarn.lock` file, so you should probably tell people to use `yarn`.
=> Remove md-primary from MdDialogConfirm's cancel button

src/core/utils/MdResizeObserver.js
**Small syntax issue**
Currently the destructor of `MdResizeObserver` is not _called_, it just _returns_ the destructor method. This leads to issues when elements that registered an `MdObserveEvent` are destroyed (e.g. in `MdTable` during `beforeDestroy` method).
This small syntax fix makes sure the destroyer method is actually called. Alternative syntax would be `destroy: () => observer.destroy()`.
=> fix(MdResizeObserver) Correctly call destructor

package.json
Removes deprecated warning when running tests.
=> remove mapCoverage jest config property from package.json (deprecated)

src/components/MdField/MdSelect/MdSelect.vue
Issue #1149 has been reproducted on v1.0.0-beta-8, after commit f0a7325 .
CSS specificity should not same as MdMenuContent.
It seems z-index on MdMenuContent overriding.
https://github.com/vuematerial/vue-material/blob/61296b366c80e47b3a36b0acd6e4e84045e0b4da/src/components/MdMenu/MdMenuContent.vue#L253-L265 
fix #1149 
thanks.
=> fix(MdSelect): re-fix select content under dialog

.github/CONTRIBUTING.md
Replace `npm` with `yarn` in contributing guide as https://github.com/vuematerial/vue-material/pull/1633#issue-177732843 mentioned.
=> docs(.github): replace npm with yarn in contributing guide

docs/app/pages/Components/Menu/Menu.vue, docs/app/pages/Components/Menu/examples/AutoClose.vue, src/components/MdMenu/MdMenu.vue, src/components/MdMenu/MdMenuContent.vue, src/components/MdMenu/MdMenuItem.vue
* new props `:md-close-on-click` option for auto close after any click event.
* `:md-close-on-click` is reactive.
* make `:md-close-on-select` reactive.
* example for props `:md-close-on-select` and `:md-close-on-click`.
~~BREAKING CHANGE: enable auto close after any click event as default~~ (Reverted)
related to https://github.com/vuematerial/vue-material/issues/1588#issuecomment-371747185
=> feat(MdMenu): new props mdCloseOnClick

src/base/base.scss
Resolves #1648
After reading few articles selector `html *` can be more performance heavy then it looks. (https://css-tricks.com/efficiently-rendering-css/)
=> perf: move universal selector from html tag

README.md
Switches from Discord's own .png to a .svg shield from [shields.io](http://shields.io/). This improves consistency with the other shields as well as the image quality.
Additionally, the label is customizable. It is currently set to `chat` but could be changed to `support` or something else.
=> fix(Readme): Improve Discord shield's quality in readme

src/components/MdField/MdFile/MdFile.vue
Empty file selection should check files' length while it exists
fix #1711
=> fix(MdFile): empty statement

docs/app/pages/Components/Checkbox/Checkbox.vue, docs/app/pages/Components/Checkbox/examples/TrueFalseValue.vue, src/components/MdCheckbox/MdCheckbox.vue, src/components/MdCheckbox/MdCheckboxMixin.js
Support `:true-value` and `:false-value` for checkboxes.
ref: https://vuejs.org/v2/guide/forms.html#Checkbox-1
There was three statements for checkbox:
* array (if `v-model` is an array)
* boolean (when `v-model` is a boolean  and `:value` is `'on'`, `v-model` is equal to `checked`)
* other (single selection. compare `v-model` with `value`. If equal, selected)
Now I change the statements to:
* array (if `v-model` is an array)
* singleSelector (if this `MdCheckbox` set a `value`, compare `v-model` with `value. If equal, selected)
* other (if `true-value` is equal to `value`, `checked`)
BREAKING CHANGE: checkbox without setting `:value` is `true` / `false` as default(was `'on'` / `null`)
fix #1701
=> feat(MdCheckBox): True / false value supporting

docs/app/pages/Components/List/List.vue, docs/app/pages/Components/List/examples/ListExpansion.vue, src/components/MdList/MdList.vue, src/components/MdList/MdListItem/MdListItemExpand.vue
> If set true, one expandable list item could be expanded at most at a time. The expanded list item will be collapsed when another is expanded.
fix #1641
=> feat(MdList): expand only one option

docs/app/pages/Components/Table/examples/TableMultiple.vue, src/components/MdTable/MdTable.vue, src/components/MdTable/MdTableCellSelection.vue, src/components/MdTable/MdTableRow.vue, src/components/MdTable/MdTableRowGhost.vue
* Remove `abstract` in `MdTableRowGhost` to make `key` works. https://github.com/vuematerial/vue-material/issues/1348#issuecomment-361845027
* Replace data `isSelected ` with computed `isMultipleSelected`.
~~BREAKING CHANGE: an available property name of the item is recommend to be sent as props `md-model-id` or it will warn.~~
~~If `md-model-id` is not set as an available property(or there is no `id` in the item as default), the `key` will be auto-generated every time. The row will be destroyed and created an new one on every update of vue lifecycle.~~
fix #1348
=> fix(MdTable): reactive selection

src/components/MdApp/MdApp.vue, src/components/MdApp/MdAppDrawer.vue, src/components/MdApp/MdAppInternalDrawer.vue, src/components/MdApp/MdAppMixin.js, src/components/MdApp/MdAppSideDrawer.vue, src/components/MdApp/MdAppToolbar.vue, src/components/MdContent/theme.scss, src/components/MdDrawer/MdDrawer.vue, src/components/MdDrawer/MdDrawerRightPrevious.vue, src/components/MdDrawer/theme.scss
Changes:
* Support right drawer with `MdApp`.
* Reactive drawer
* changing width
* swap right / left
* toggle drawer via `v-if`
* Replace useless props `mdLeft` with `!this.mdRight`.
My test case:
```vue
<template>
<div class="page-container md-layout-column">
<md-app>
<md-app-toolbar class="md-primary"><span class="md-title">Title</span></md-app-toolbar>
<md-app-drawer :md-active.sync="open" md-persistent="full" :md-right="swap" v-if="left" :style="{width: width ? '100px' : '200px'}" style="min-width: 100px">
<md-toolbar class="md-transparent" md-elevation="0">Left nav</md-toolbar>
<md-switch v-model="open"></md-switch>
</md-app-drawer>
<md-app-drawer :md-active.sync="open" md-persistent="full" :md-right="!swap" v-if="right" style="width: 100px">
<md-toolbar class="md-transparent" …
```
=> fix(MdApp): right drawer, fully reactive

src/components/MdTable/MdTable.vue
Simple table without v-model is rendering default slots 2 times.
Reproduction: https://codesandbox.io/s/1qy64o65j?module=App.vue
=> fix(MdTable): fix double default slots

src/components/MdApp/MdApp.vue
Fixes #1741 
* `child.data.attrs` needs to be checked for existence.
* Broken out into a separate function called `generateAttrKeys` to avoid the following ESLint complexity error (limit at 6):
```
vue-material/src/components/MdApp/MdApp.vue
38:24  error  Arrow function has a complexity of 8  complexity
```
=> fix(MdApp): child.data.attrs is undefined

docs/app/pages/Components/List/List.vue, docs/app/pages/UiElements/Layout/Layout.vue
=> docs: corrections of breakpoints

src/components/MdField/MdFile/MdFile.vue
Using `@focus` on md-file would trigger an infinite loop of the file picker by re-sending the focus event as soon as the file picker closed.
Resolves #1677
=> Resolve #1677 (infinite file picker loop)

docs/app/pages/Components/Radio/Radio.vue, docs/app/pages/Components/Radio/examples/RegularRadio.vue, src/components/MdRadio/MdRadio.vue
=> feat(MdRadio): object support

src/components/MdTable/MdTable.vue, src/components/MdTable/MdTableRow.vue
assigning value instead of mutating value to avoid unexpected behavior
fix #1786
=> fix(MdTable): provide value mutation

src/components/MdTable/MdTable.vue
`asc` / `desc` directions are wrong. `asc` should be less to more.
=> fix(MdTable): reverse asc direction

src/components/MdSnackbar/MdSnackbarQueue.js
This modifies createSnackbar() to receive 3 arguments and pass the 3 arguments to createPromise(), as indicated by the function signature of createSnackbar() and createPromise(). This fixes #1791
=> fix(MdSnackbar) add "persistent" argument to calls to createPromise() #1791

docs/app/pages/Components/SpeedDial/examples/PositionDirection.vue
I changed the demo to a better way in my opinion.
I don't think `z-index` is the best solution because there might be some other components with `z-index` higher than `2`, than you should put higher `z-index` for that. You'll never know how high the components the Vue Material user put in the content. In this case, you'll always need to add a higher `z-index` for that. So, set `z-index` is a solution only for the demo case.
The demo render as unexpected is just because the speed dials are append before the buttons. If they are after the buttons it would looks fine.
Additionally, I replace the native buttons with Vue Material buttons.
related to #1764
=> docs(SpeedDial): better position direction demo

src/components/MdList/MdListItem/MdListItem.vue, src/components/MdList/MdListItem/MdListItemExpand.vue, src/components/MdList/theme.scss
Fixes #1643 
Default expanded list structure:
```sass
.md-list-item-container
.md-list-item-content <-- hover, pointer if expand
.md-list-expand
.md-list
.md-list-item
.md-list-item-container
.md-list-item-content <-- no hover, no pointer
```
* Specifically target direct `.md-list-item-content` children of `.md-list-item-container:not(.md-list-item-default)` to use hover. This eliminates the whole expanded list getting hover-effects.
* If `.md-list-item-container` is expand and `:not(.md-list-item-default)`, apply hover to direct `.md-list-item-content` children, giving topmost list-element in expandable hover.
* Specifically target direct `md-list-expand-icon` children when parent is `.md-active`.
May interfere with pending PR #1760
=> fix(MdListItem): expand content cursor style and hover

src/components/MdField/MdTextarea/MdTextarea.vue
It was only resize when changed from component inside before.
If you change value via `v-model` it would not be changed.
With this fix, textarea will auto-resize whenever `localValue` changed, both from inside or outside.
fix #1833
=> fix(MdTextarea): resize whenever localValue changed

src/theme/all.scss
`@import "../components/MdTabs/theme"  `repeating on src/theme/all.scss.
=> fix MdTabs repeat import in all.scss #TimRChen

docs/app/pages/Components/Input/Input.vue
Typos fixed. 
Corrected the field object in data as the api-table was not showing. 
Added missing description for md-counter boolean to hide the count display. Issue #1847
=> docs(Input): Typos and Correction

src/components/MdTable/MdTable.vue
The current implementation couldn't handle selection data and table data at the same time, or having selection data before table data #1866
Case 1: Update at same time
https://codesandbox.io/s/lp7117wylq
Case 2: Give selection AOT
https://codesandbox.io/s/6j7n78mz6z
docs/app/App.vue for case 2
```
<template>
<div>
<md-table v-model="people" md-card
@md-selected="onSelect" :md-selected-value.sync="selected">
<md-table-toolbar>
<h1 class="md-title">With auto select and alternate headers</h1>
</md-table-toolbar>
<md-table-toolbar slot="md-table-alternate-header" slot-scope="{ count }">
<div class="md-toolbar-section-start">{{ getAlternateLabel(count) }}</div>
<div class="md-toolbar-section-end">
<md-button class="md-icon-button">
<md-icon>delete</md-icon>
</md-button>
</div> …
```
=> comp(mdTable): nextTick selection data

docs/app/pages/Components/Table/Table.vue
=> docs(Table): fix grammar issues

.github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE.md, README.md, ROADMAP.md, docs/app/banner.js, docs/app/pages/About.vue
Apply discord vanity URL and remove Slack link because the invite link is expired.
=> chore: apply discord vanity URL

src/core/utils/MdRouterLinkProps.js
=> Fix new router-link registration name #1977

src/components/MdSvgLoader/MdSvgLoader.vue
If invalid svg or svg without valid mimetype was given, the module crashed when verifiying the svg file in the isSVG method.
I have fixed this with a little check to ensure that mimetype is valid, before checking if it's an svg.
=> bugfix svg loader for invalid / missing mimetype

src/components/MdRipple/MdWave.vue
This fixes #2033 .
The problem appeared to be the start of the <transition> element not triggering because the condition (animating) was true at initialization. Moving it to the mounted callback fixes it.
=> fix(MdRipple): fixed missing ripple effect

src/components/MdRipple/MdWave.vue
Fixes #2033 
Probably should use `TransitionGroup` instead of single transitions as recommended in docs https://vuejs.org/v2/guide/transitions.html
=> [MdWave] quick fix for transitions in vue@2.6.10

src/components/MdCheckbox/MdCheckbox.test.js, src/components/MdSwitch/MdSwitch.test.js
Test suite is failing due to label selectors not triggering the proper events for MdCheckbox and MdSwitch tests. Converted tests to use container selectors found in other functioning tests within the same files.
Hopefully this helps with the backlog of PRs that are all failing!
=> test: fix test selectors for checkbox and switch

src/components/MdField/MdField.vue
Password on/off toggle icon showing the wrong icon for the hide/show password state. 
When the password is hidden the icon should have the eye with the line through it, when the password is visible/plain text, the icon should be the eye with no line.
Steps to reproduce:
- Create md-field component with password input field
- Toggle will show eye with no line for hidden password
- Hit password toggle, eye with line through will show for visible password
Vue-material => https://i.imgur.com/H3YkZqV.png (current bug)
Material.io => https://i.imgur.com/chsuQY3.png (correct usage)
=> invert password on-off icons

src/components/MdField/MdSelect/MdSelect.vue
Fixes  #2000
Just removed id attribute from `<md-input>` to leave it only on `<select>`
=> fixFixed non unique ids on MdSelect

src/components/MdField/MdSelect/MdSelect.vue
I guess it was just a typo, but it causes page crash, when no `v-model` prop was provided to `<MdSelect multiple/>`.
Reproduction link https://codesandbox.io/s/moz0535o8j
**WARNING Page will crash**
=> fix(MdSelect): infinite loop error, when no v-model provided

src/components/MdDatepicker/MdDatepickerDialog.vue
Fixes #1794 #1915 
The issue occurs when DatePicker used inside flex-container with width less than datepicker width. 
On the first frame of its existence datepicker container shrinks to fit inside flex container. It results in increased height (cause content adapts). This increased height is caught by popper.js and position calculates incorrectly
=> fix(MdDatepicker): positioning when used inside flex container

docs/app/pages/Components/Datepicker/examples/BasicDatepicker.vue, docs/app/pages/Components/Datepicker/examples/MultiTypesDatepicker.vue, docs/app/pages/Configuration.vue, package.json, src/components/MdDatepicker/MdDatepicker.vue, src/material.js, yarn.lock
This PR fixes incorrect datepicker behavior after #1698 was merged.
`date-fns` is updated to latest version, date formats changed according to new docs.
Also fixed a typo (I believe) in dateFormat method, formatting a string value instead of Date object
=> refactor(MdDatepicker): upgrade date-fns

docs/app/pages/Components/Tooltip/examples/Dynamically.vue
In the documentation for dynamic tooltips, it shows the tooltip with the text "Top". This text should be "Bottom" since the tooltip is actually being shown below the icon.
=> docs: fix dynamic tooltip text to show bottom instead of top

src/components/MdTable/MdTable.vue
When sorting a md-table component if a cell contains undefined or null data an error is logged.
Referencing issue #1906
=> fix(MdTable): undefined table sorting #1906

.gitignore, docs/app/pages/Components/Autocomplete/examples/AutocompleteSearch.vue
also fixed wrong empty state text
before:
after:
=> docs: fix 2 wrong property names with autocomplete docs

src/components/MdProgress/MdProgressSpinner/MdProgressSpinner.vue
It seems Vue cannot detect animation/transition end because of infinite animation at https://github.com/vuematerial/vue-material/blob/dev/src/components/MdProgress/MdProgressSpinner/MdProgressSpinner.vue#L260.
Use reverse animation for leave state instead.
Fix #1935
=> fix(MdProgressSpinner): improve transition

src/components/MdMenu/MdMenuContent.vue
Fixes #2052. Wrong method was used to check if event target belongs to menu
=> fix(MdMenu): unexpected close on item click

package.json
Used [this](https://github.com/facebook/jest/issues/3630) to fix the errors that everyone seems to have in their PR's CI tests.
=> test: add a "testURL" field to jest config

src/components/MdTabs/MdTabs.vue
content and indicator were not initializing to the set active tab
=> [MdTabs] fix mdActiveTab not selecting set tab on load

src/components/MdTabs/MdTabs.vue
added rtl support to md-tabs component with mdIsRtl prop.
when in RTL the tab was moving to the wrong direction with the "transform: translate3D" property.
we created a hard coded fix in our project and it was making our life miserable, it would be awesome if this feature could be added.
=> [core] RTL support #80

src/components/MdMenu/MdMenuContent.vue
This should fix issues like #2200 
I think observers should be created at the end of the loop, when initial click event already gone. This prevents closing on initial render due to bubbling click event from trigger.
=> fix(MdMenu): fix to prevent menu click observers on render

src/components/MdApp/MdAppContent.vue
Title says it all. You can see an example of the problem on the docs page.
https://vuematerial.io/components/app
Check the Fixed Toolbar. After scrolling down, you can see that the border-left of app-content is being left when scrolling.
You can also check the dev tools. The app-content is not the content's height but rather the container's
=> fix(MdApp): remove height 100 to make md-app-content span content height

src/components/MdDatepicker/MdDatepicker.vue
Currently, it is not possible to catch the md-clear event, that comes from MdField and is not propagated by MdDatepicker. Therefore, I added a handler for 'md-clear', which emits the same event.
Currently, the MdDatepicker is always clearable. I added a prop to allow changing this, while 'true' is still the default.
=> Fix(MdDatepicker): Propagate clear event

docs/app/pages/Components/Input/examples/Counters.vue, src/components/MdField/MdFieldMixin.js
fixes #2054
The solution was simply to add an event listener to the element parent form and to "clear" the field on `reset` events.
I also changed the doc example a bit to demonstrate this.
=> fix(MdField): fix the character counter not reseting when reseting the form

src/components/MdRipple/MdRipple.vue
https://github.com/vuematerial/vue-material/blob/dev/src/components/MdRipple/MdRipple.vue#L55
```js
const isEvent = active.constructor.toString().match(/function (\w*)/)[1].toLowerCase() === 'mouseevent'
```
MouseEvent.constructor.toString() in chrome is `function MouseEvent() { [native code] }`, but IE11 returns `[object MouseEvent]`
=> Fix mdButton clicks error in IE11

src/components/MdMenu/MdMenuContent.vue
When clicking the backdrop of `mdMenu`, IE11 will whine about missing the Node.contains method and cause the menu to stay opened. Actually not all nodes in IE have contains method, for example svg and empty text node. This patch tends to use `compareDocumentPosition` instead when contains method does not exist.
https://github.com/react-bootstrap/dom-helpers/issues/11
https://github.com/ProseMirror/prosemirror/issues/605
=> fix undefined contains method in IE11

src/components/MdField/MdSelect/MdOption.vue
The docs for MdSelect (https://vuematerial.io/components/select/) state that MdOption value may be a boolean, and therefore may be `false`. However, when the value of `false` is passed in, and the option subsequently selected, there is no value rendered (just `''`).
This is because of this line, which isn't letting options with value as `false` be registered in the parent `MdSelect.items` map.
Small fix, but it now renders correctly.
=> Allow false as a value for an MdOption

docs/app/pages/Components/Chips/Chips.vue, docs/app/pages/Components/Chips/examples/AutoInsert.vue, src/components/MdChips/MdChips.vue
**Modify only MdChips component**
The function of automatically adding a chip is implemented if focus is lost.
Reason for adding: users often forgot to press enter, just submitted the form. Consequently, the data was lost. There is no programmatic way to get user input, so I added a new option
Thanks
=> Auto insert in MdChips after focusout

docs/app/template/MainNav.vue
Table of contents in docs is mispositioned on smaller heights.
=> Fixed docs position and height

src/components/MdField/MdFieldMixin.js
The MdSelect component is using a mixin (`MdFieldMixin.js`) that was causing a badInput error, even though this badInput validation was intended to fix #2108, it caused some unwanted side-effects, like this error.
In this commit I just added a check to see if the validation property exists.
=> Fixed badInput error message for MdSelect (#2285)

src/components/MdTable/MdTable.vue
The current table comparator does not work if one of the element is the `0` because of #2012.
In general the current comparator is less robust than it could be so I just re-wrote it from scratch.
I'm also piggybacking a small fix to the `getObjectAttribute` function.
See https://jsfiddle.net/tb6swf5g/13 for a live example of this new comparator.
=> Fix mdtable comparator

package.json
Please check the https://github.com/isy/vue-toc/pull/8 I did on vue-toc. It was bringing a lot of issues with having vue as pure dependency.
This is the only change (moving vue to peerDependency) same as in vue-material.
Without it would end up with two vue packages (if vue-material is not at the same depth as the main app) which would break reactivity and bring many other nasty errors
Here is the issue: #2280
=> Bumped up the vue-toc ver to avoid breaking reactivity

src/components/MdDatepicker/MdDatepicker.vue
Hello, 
I noticed that there is a forgotten `this`  in the template of the `MdDatepicker` component on conditionally adding `md-native` class
=> fix(MdDatepicker): remove  in template

src/components/MdDatepicker/MdDatepicker.vue, src/components/MdDatepicker/MdDatepickerDialog.vue
The date-picker dialog would not close even if focus moves out of the datepicker input field.
I have added a focus-out event listener instead of blur event listener. If the new focus is within the datepicker, then the dialog will remain open. But if the new focus is outside the datepicker, then dialog will close.
=> fix(MdDatePicker): close datepicker on blur - fixes issues #2371, #2343

docs/app/pages/Components/Tabs/Tabs.vue, docs/app/pages/Components/Tabs/examples/TabsOrdering.vue, src/components/MdSteppers/MdStep.vue, src/components/MdTabs/MdTab.vue, src/components/MdTabs/MdTabs.test.js, src/components/MdTabs/MdTabs.vue
This merge request fixes #2282 (and possibly also fixes #2015).
I heavily rebased to have one (small, meaningful and easy-to-review) commit per fix/feat.
Tell me what you think about it all.
There is a remaining WIP commit.
That commit is for you to visually test the behaviors before (by checking out the commit) and after (by checking out the branch) the bug fixes (same goes for unit tests before and after).
This big example lists all the possible edge case I could find, in order to do my best to not introduce a regression in the library.
I will remove that commit before merging.
Or if you have a private testbed where I could put the example's content, it would be even cooler: it is so easier to visually test weird edge-cases are correctly handled...
Unit tests are good for that too, but …
=> Fix/md tabs/ordering
