vuematerial/vue-material

src/components/mdButton/mdButton.vue

Hi Marcus,
Here is a fix for issue 41.
Congratulations for your excelent work!
Regards,
Paulo

Fix for issue #41 (md-button ignores type prop)

---

src/components/mdCheckbox/mdCheckbox.vue
src/components/mdRadio/mdRadio.vue

Please do the same for other clickable/changeable components. Thanks :)

pass on  DOM event for checkbox and radio

---

docs/src/pages/components/BottomBar.vue
src/components/mdBottomBar/mdBottomBar.scss
src/components/mdBottomBar/mdBottomBar.theme
src/components/mdBottomBar/mdBottomBarItem.vue
src/core/stylesheets/typography.scss

add href support for mdBottomBar

---

docs/src/pages/components/Dialog.vue

Update prompt code example to be a prompt

---

src/components/mdTable/mdTablePagination.vue

Fix table pagination

---

src/components/mdTabs/mdTabs.vue

Fix issue #165 by using for...in instead of Object.values()
This bug also appears in Safari (original Issue only on IE).

[fix] md-tabs in IE/Safari + Fix tab @change event emitted

---

docs/src/pages/components/Card.vue
src/components/mdCard/mdCard.theme

Added a simple change to be able to add theme on a entire card or in each internal component independently

Support for theming on Cards

---

docs/src/pages/components/Tabs.vue
src/components/mdTabs/mdTab.vue
src/components/mdTabs/mdTabs.vue

Improvement in md-tabs : Can display a tooltip (md-tooltip) on the tab header.
+ Doc update

[new] md-tabs improvements : md-tooltip

---

docs/src/App.vue
docs/src/config.js
docs/src/pages/components/Spinner.vue
docs/src/routes.js
src/components/mdSpinner/index.js
src/components/mdSpinner/mdSpinner.scss
src/components/mdSpinner/mdSpinner.theme
src/components/mdSpinner/mdSpinner.vue
src/index.js

create spinner #20

---

docs/src/pages/components/Icon.vue

- Added a notice for icons with spaces in their name
- Removed an unfinished sentence.

Improve the icon component documentation

---

src/components/mdList/mdListExpand.vue

fix expansion lists size on resize #278

---

src/components/mdInputContainer/mdTextarea.vue

autosize needs to run after nextTick to resize properly.

fixes #336 run autosize on nextTick

---

docs/src/pages/components/BottomBar.vue
src/components/mdBottomBar/mdBottomBarItem.vue

Hello!
This pull request intends to expose to the bottom bar the new options available to use as source of the icons.
Please review and provide feedback, i'll kindly attend any request which makes this improvement find his way.
For your time thank you.

adding to the bottombar the new icon options

---

src/components/mdSpeedDial/mdSpeedDial.scss

Since you are already using `pointer-events` in the project I figure it's fair game. 
This seems to be the simplest way to solve #419.

Fix #419: remove pointer-events from hidden buttons

---

src/components/mdSnackbar/mdSnackbar.vue

Implement pausing and resuming

---

docs/src/pages/components/Sidenav.vue
src/components/mdSidenav/mdSidenav.vue

Implement swipe on Sidenav

---

src/core/components/mdInkRipple/mdInkRipple.vue

Fixed the issue from [here](https://github.com/marcosmoura/vue-material/issues/477), about the ink ripple component not working with touchscreen computers.

Fixed ripple effect on touchscreen desktops (#477).

---

docs/src/pages/components/Chips.vue
src/components/mdChips/mdChips.theme

Added themed Chips.
#497 
What do you think?

Themed Chips

---

src/components/mdSpeedDial/mdSpeedDial.vue

Fixed this bug on speed dial.
[bug](https://gitlab.fiws.net/fiws/test-acdc/uploads/94ae2540c87e9cbe4118b5dda73e2e9c/vue-material-speed-dial.mp4)

fixed weird behaviour of speed dial #484

---

docs/src/components/ApiTable.vue
docs/src/pages/components/Tabs.vue
src/components/mdTabs/mdTab.vue
src/components/mdTabs/mdTabs.vue

Allow customize tab's header item using slot in `md-tabs` component.

Allow customize tab item using slot

---

docs/src/pages/ui-elements/Layout.vue
src/components/mdLayout/mdLayout.scss
src/components/mdLayout/mdLayout.vue

Hey, i work around with layout and for me is missing vertical aligment for layouts. I think is useful for many things.

Added vertical align to layout

---

src/components/mdCheckbox/mdCheckbox.scss
src/components/mdRadio/mdRadio.scss

[md-checkbox/md-radio] Add pointer cursor

---

src/components/mdTable/mdTablePagination.vue
src/core/components/mdTheme/index.js

Accent and background hue was always set to default value.
Solves issue https://github.com/marcosmoura/vue-material/issues/533.

Fix - when to use default colorVariant

---

README.md
docs/src/pages/components/BottomBar.vue
docs/src/pages/components/Buttons.vue
docs/src/pages/components/Checkbox.vue
docs/src/pages/components/Chips.vue
docs/src/pages/components/File.vue
docs/src/pages/components/Input.vue
docs/src/pages/components/List.vue
docs/src/pages/components/Menu.vue
docs/src/pages/components/Radio.vue
docs/src/pages/components/Select.vue
docs/src/pages/components/SpeedDial.vue
docs/src/pages/components/Switch.vue
docs/src/pages/components/Tabs.vue
docs/src/pages/themes/DynamicThemes.vue
src/components/mdTable/mdTableHead.vue

I ran through the site and fixed all the instances I found.

Fix Made language more gender neutral #633

---

src/components/mdTabs/mdTabs.scss

Fix md-tabs not properly flexed when applied with md-fixed

---

docs/src/pages/components/List.vue

The code format followed the guideline in the other Components.
Thanks for this useful library!

Added the omitted code samples for Demo in List Components (Multiple options, Multiple Expand)

---

src/components/mdSnackbar/mdSnackbar.scss

Those lines seems to be legacy lines (compare to 121-179).

Fix floating action button incoherent move #713

---

package.json
src/components/mdSpinner/mdSpinner.vue

fixed when npm install  extract-text-webpack-plugin@beta not  found error ( #665 )

---

src/components/mdMenu/mdMenuContent.vue

md-slect: key navigation ignores mdSubheader onEnter (#592)

---

src/components/mdSwitch/mdSwitch.vue

mdSwitch can be used without v-model (#607)

---

docs/src/pages/components/Chips.vue
src/components/mdChips/mdChips.scss
src/components/mdChips/mdChips.vue

Hi, I would like remove required chip-template and make md-error possibility.

md-error possibility and remove required chip-template within md-chips

---

src/components/mdCheckbox/mdCheckbox.scss

Fixed the issue #624 .
Thank you for the suggestion @davidhooey !

fix on issue #624 - Checkbox shrink if text is too long

---

docs/src/pages/components/List.vue

List.vue enhanced with examples

---

docs/src/pages/components/Input.vue
src/components/mdInputContainer/common.js
src/components/mdInputContainer/mdInput.vue
src/components/mdInputContainer/mdTextarea.vue

Issue 744 - Added readonly attr on mdInput and mdTextarea

---

docs/src/pages/components/Select.vue
src/components/mdSelect/mdOption.vue
src/components/mdSelect/mdSelect.scss
src/components/mdTable/mdTablePagination.vue

Follow-up for #536. Re-open PR from develop branch.
Note: This also contains a fix for the table pagination component.

Fix for #529. Updated docs with an example of disabled items in the Select component.

---

src/components/mdSwitch/mdSwitch.vue

The tab passed twice by mdSwitch

Add tabindex -1 to the input inside the switch

---

src/core/components/mdTheme/mixin.js

Fix default theme not applying

---

docs/src/pages/components/Select.vue
src/components/mdSelect/mdSelect.scss
src/components/mdSelect/mdSelect.vue

Add ability to use icon for select. Also provide a new md-menu-options prop to pass options to menu within select.

Add ability to use icon for select component.

---

docs/src/index.js
package.json

Possible fix of issue #459 
> Testing needs to be made.

Added babel-polyfill into project

---

docs/src/pages/components/Onboarding.vue
src/components/mdOnboarding/mdBoards.scss

I fixed the OnBoarding screen layout

update layout functionality onBoard

---

src/components/mdCard/mdCard.scss
src/components/mdCard/mdCardExpand.vue

Fixed issue #803

---

src/components/mdStepper/mdStepper.scss

I fixed the icon of Stepper screen

fixed stepper icon

---

docs/src/pages/components/Input.vue
src/components/mdInputContainer/common.js

Fixes logaretm/vee-validate#588.

Add blur and focus events to md-input

---

src/components/mdTable/mdTable.vue

fixing bug. issue #869

---

docs/src/pages/components/Tabs.vue

[![screenshot from 2017-07-10 12-09-37](https://user-images.githubusercontent.com/9481405/28001593-b509987e-6568-11e7-9cc7-452b006410ca.png)](http://vuematerial.io/#/components/tabs)

Fix syntax errors

---

docs/src/pages/components/Stepper.vue

Added missing events to the stepper documentation and fixed md-back-continue typo (#890 and #902)

Fixed stepper doc

---

docs/src/components/ReleaseVersion.vue
src/components/mdSelect/mdOption.vue
src/components/mdSelect/mdSelect.vue

fixed issued #910

---

docs/src/pages/components/Select.vue
package.json
src/components/mdInputContainer/mdAutocomplete.vue

updating vue and fixing :key issue on v-for

---

package.json

udating webpack and vue dependencies

---

src/components/mdSelect/mdSelect.vue

fix issue #908

---

src/components/mdSelect/mdSelect.scss

Fixed issue #903

---

docs/src/pages/GettingStarted.vue

Fixing issue #902

---

docs/src/pages/GettingStarted.vue

Fixing issue #899

---

build/webpack/prod-docs.js

enhancing code

---

src/components/mdTable/mdTable.vue
src/components/mdTable/mdTablePagination.vue
src/components/mdTable/mdTableRow.vue

Update selection handling of md-table

---

docs/src/pages/components/Input.vue
docs/src/pages/components/Menu.vue
docs/src/pages/components/Tabs.vue
src/components/mdInputContainer/mdAutocomplete.vue
src/components/mdMenu/mdMenu.theme
src/components/mdMenu/mdMenu.vue
src/components/mdMenu/mdMenuContent.vue
src/components/mdMenu/mdMenuItem.vue
src/core/utils/autocomplete-common.js
src/core/utils/getInViewPosition.js

After long await, the fixes are ready to be merged into `develop`. Here is a list of fixes:
- Input no longer blurred by `md-menu`
- Items can now be selected with the keyboard (arrow-keys and return)
- The maximum height of the menu can now be set to be either dependent on window height or the number of items in the list
- Menu stays put to the bottom of the input
- Menu is resized to width of trigger element (input)
I have also provided an example in the Input page of the documentation and have updated the API tables.
I would highly encourage for anyone to test this before merging as there may be issues I have not noticed.
To those with write access, **do not merge this pull request at any cost unless I specify in a comment to this PR that it is ready to be merged. This is because I …

Fix various issues with md-autocomplete (issue #895)

---

src/components/mdInputContainer/mdInputContainer.scss

fixes weird asterisks in IE

---

src/components/mdSnackbar/mdSnackbar.vue

In some rare occasions, the snackbar wouldn't open with the previous changes to it. Now that's fixed.

Fix snackbar, again

---

src/components/mdSelect/mdSelect.vue

Fixing multiselect issue that checked checkboxs won't be unchecked while the value props changed.
Issue #997

Fixing issue #997

---

src/components/mdCard/mdCard.theme

Fix theme bug in issue #906

---

docs/src/pages/components/Snackbar.vue
src/components/mdSnackbar/mdSnackbar.vue

Assign `Infinity` to mdDuration to disable auto closing.
Issue: #790

[mdSnackbar] Infinity duration

---

src/components/mdInputContainer/mdAutocomplete.vue

Fixing the autocomplete fix PR

---

docs/src/pages/GettingStarted.vue

Fixed misspellings

---

docs/src/pages/components/Input.vue
src/components/mdInputContainer/mdAutocomplete.vue
src/components/mdList/mdListItemExpand.vue
src/components/mdMenu/mdMenu.vue
src/components/mdMenu/mdMenuContent.vue
src/components/mdMenu/mdMenuItem.vue
src/components/mdOnboarding/mdBoards.vue
src/components/mdSelect/mdSelect.vue
src/components/mdStepper/mdStepper.vue
src/components/mdTabs/mdTabs.vue
src/core/utils/autocomplete-common.js

ESLint autoFix codeStyle

---

.github/CONTRIBUTING.md
README.md

Warning: readme.md in master already changed the link. There will be a conflict when  merged developer to maste

Has changed chat link from gitter to slack

---

.github/CONTRIBUTING.md

move from npm to yarn

---

src/components/mdInputContainer/mdTextarea.vue

[md-textarea] fix name attribute #1030

---

docs/src/pages/components/Checkbox.vue
src/components/mdCheckbox/mdCheckbox.vue

This adds the ability to use an Array in the v-model for MdCheckbox. It provides the same functionality as Vue's [basic input](https://vuejs.org/v2/guide/forms.html#Checkbox).
This is a requested feature documented here: https://github.com/vuematerial/vue-material/issues/414

#414 Checkbox accept Array as v-model

---

src/components/mdTable/mdTablePagination.vue

Initial currentPage by mdPage.
[Reproduction](https://codepen.io/VdustR/pen/qPBQxb)

[mdTable] Pagination Issue

---

docs/src/pages/components/Select.vue

Added / to en tag in documentation for md-select

Fix for mdSelect documentation #1043

---

docs/src/pages/components/Input.vue
src/components/mdInputContainer/common.js
src/components/mdInputContainer/mdInput.vue

Hi.
Now, md-input component does not have min and max attribute.
but In contrast, maxLength, placeholder, required and etc are supported like real input element.
So I think that md-input should also support attributes such as max and min.
About min and max, reference [here](https://www.w3schools.com/tags/att_input_min.asp)
thanks.

support min and max for md-input

---

docs/src/pages/components/Tabs.vue

corrected a typo

---

src/components/mdInputContainer/mdAutocomplete.vue

Per @waratah 's request, I have created a commit and pull request to fix the issue with autocomplete throwing an error on focus if empty.
Fix: https://github.com/vuematerial/vue-material/issues/1054

Fix #1054: [mdInput] Autocomplete focus error

---

build/docs/webpack.js
build/lib/webpack.js
docs/app/components/SplashContainer.vue
package.json
yarn.lock

docs: automatic preload assets

---

README.md

doc(README.md): make more consistened with the website

---

src/components/MdField/MdFile/MdFile.vue

fix(MdFile): Remove calling method `onInput` which doesn't exist

---

build/lib/index.js
build/lib/webpack.js
src/components/MdField/MdSelect/MdSelect.vue
src/components/MdMenu/MdMenuContent.vue
src/components/MdPortal/MdPortal.js
src/components/MdRipple/MdRipple.vue
src/core/MdTheme.js
src/core/mixins/MdFocused/MdFocused.js

feat: add wide support for server side rendering

---

docs/app/pages/Components/File/File.vue

Updated file doc. Typo in event name md-change

---

src/components/MdChips/MdChips.vue

trim input value while inserting
fix #1207

fix(MdChips): make chip allow spaces

---

src/components/MdAutocomplete/MdAutocomplete.vue

fix(MdAutocomplete): Initial and update `searchTerm` via `v-model`

---

.github/config.yml
.travis.yml
README.md

chore: change old repository name to new

---

src/components/MdDatepicker/MdDatepickerDialog.vue

fix(MdDatepicker): show today if date is not selected

---

src/components/MdProgress/MdProgressSpinner/MdProgressSpinner.vue

Firefox doesnt like CSS property `r`, change to attribute instead

 fix(MdProgressSpinner): fix firefox radius

---

docs/app/pages/GettingStarted.vue
docs/app/pages/Themes/Configuration.vue

docs: add note for themes, example with CDNs

---

docs/app/pages/Components/Select/Select.vue
src/components/MdField/MdSelect/MdSelect.vue

https://github.com/vuematerial/vue-material/issues/1233

feat(MdSelect): add md-opened, md-closed events

---

docs/app/pages/Themes/Configuration.vue

Fix missing commas in Theme configuration

---

docs/app/pages/Components/App/App.vue

Was previously linked to md-drawer.

fix(docs): Fixes link from md-app to md-content

---

docs/app/pages/Components/Datepicker/Datepicker.vue
docs/app/pages/Components/Datepicker/examples/LabeledDatepicker.vue
src/components/MdDatepicker/MdDatepicker.vue

feat(MdDatepicker): add label option

---

src/components/MdField/MdSelect/MdSelect.vue

fix(MdSelect): emit `md-selected` event after `localValue` changed

---

src/components/MdAutocomplete/MdAutocomplete.vue

fix(MdAutocomplete): fix input emit when cleared

---

src/components/MdTable/MdTable.vue

Fixes an error that makes it impossible to sort by an attribute of a child object.

Fix error to sort by attribute of child object

---

src/components/MdField/MdField.vue

fix(MdField): disable clear button while field is disabled

---

src/components/MdChips/MdChips.vue

let developers choose what to show from outside
fix #1327

fix(MdChips): slot for static chips

---

docs/app/pages/Components/Autocomplete/examples/AutocompleteAsync.vue
docs/app/pages/Components/Autocomplete/examples/AutocompleteBox.vue
docs/app/pages/Components/Autocomplete/examples/AutocompleteTemplate.vue
docs/app/pages/Components/Autocomplete/examples/AutocompleteTrigger.vue
docs/app/pages/Components/Drawer/examples/Temporary.vue
docs/app/pages/Components/Input/examples/InlineActions.vue
docs/app/pages/Components/List/examples/Controls.vue
docs/app/pages/Components/List/examples/ListTypes.vue
docs/app/pages/Components/Select/examples/BasicSelect.vue
docs/app/pages/Components/Select/examples/DenseSelect.vue
docs/app/pages/Components/Select/examples/DisabledSelect.vue
docs/app/pages/Components/Select/examples/MultipleSelect.vue
docs/app/pages/Components/Table/examples/TablePaginationSoon.vue
docs/app/pages/Components/Table/examples/TableSearch.vue
docs/app/pages/Components/Tabs/examples/TabIcons.vue
docs/app/pages/Components/Toolbar/Toolbar.vue
docs/app/pages/Components/Toolbar/examples/ContentActions.vue
docs/app/pages/Home/icons/HomeIconDevices.vue
docs/app/pages/UiElements/Layout/Layout.vue
src/core/icons/MdCheckIcon.vue
src/core/icons/MdUpwardIcon.vue

fix: components name

---

src/components/MdField/MdSelect/MdSelect.vue

make dense props available
fix #1332

fix(MdSelect): fix dense

---

src/components/MdTable/MdTable.vue

fix(MdTable): number sorting

---

src/components/MdDialog/MdDialog.vue

fix(MdDialog): flexbox issue with IE

---

src/components/MdDatepicker/MdDatepickerDialog.vue

fix(MdDatepicker): duplicate keys

---

src/components/MdField/MdField.vue
src/components/MdField/MdSelect/MdSelect.vue

fix(MdSelect): prevent overflowing arrow icon

---

docs/app/pages/Components/Autocomplete/Autocomplete.vue
docs/app/pages/Components/Form/examples/FormValidation.vue
docs/app/pages/Components/Select/examples/BasicSelect.vue
docs/app/pages/Components/Select/examples/DenseSelect.vue
docs/app/pages/Components/Select/examples/DisabledSelect.vue
docs/app/pages/Components/Select/examples/MultipleSelect.vue
docs/app/pages/Components/Select/examples/OptgroupSelect.vue

Updated older layout classes to new

docs: refactor to new layout

---

src/components/MdApp/MdApp.vue

feat(MdApp): allow custom components with slot

---

src/components/MdTable/MdTableRow.vue

feat(MdTableRow): pass native events

---

src/components/MdSteppers/MdSteppers.vue

fix(MdSteppers): overflow on resize

---

src/components/MdField/MdField.vue

fix(MdField): Consider number `0` as hasValue

---

docs/app/pages/Components/Dialog/Dialog.vue

docs(MdDialog): add note about scrollable content

---

src/components/MdDatepicker/MdDatepicker.vue

Resolves https://github.com/vuematerial/vue-material/issues/1287#issuecomment-353984365

feat(MdDatepicker): remove fixed label position

---

src/components/MdDatepicker/MdDatepicker.vue

feat(MdDatepicker): add dateformat

---

docs/app/pages/Components/List/examples/ListExpansion.vue
src/components/MdList/MdListItem/MdListItem.vue
src/components/MdList/MdListItem/MdListItemExpand.vue

new props `md-expanded` with sync to make expansion reactive
fix #1425

feat(MdListItemExpand): reactive expansion

---

src/components/MdRipple/MdRipple.vue

Fix for clearing ripples if its called programatically.

fix(MdRipple): clear ripples if called programatically

---

docs/app/pages/Components/Tabs/Tabs.vue

docs(MdTabs): add missing md-icon prop

---

src/components/MdTooltip/MdTooltip.vue

fix(MdTooltip): overlaying in dialog

---

build/new-component.js

* fix - prefix name `Doc` for new doc component.
* fix - doc component directory path case.

fix: new component script

---

src/components/MdLayout/mixins.scss

fix(MdLayout): remove breakpoint margins

---

docs/app/pages/Components/Menu/examples/Directions.vue

https://vuematerial.io/components/menu

fixed spelling misstake

---

src/components/MdField/MdField.vue

fix(MdField): fix font size

---

src/components/MdTable/MdTableRow.vue

fix(MdTableRow): update selectableItem while `mdItem` changed

---

src/components/MdDatepicker/MdDatepickerDialog.vue

feat(MdDatepicker) datepicker as dialog on mobile

---

docs/app/pages/Components/Snackbar/Snackbar.vue
src/components/MdSnackbar/MdSnackbar.vue
src/components/MdSnackbar/MdSnackbarQueue.js

fix(MdSnackbar): keep alive if its persistent

---

docs/app/pages/Components/Checkbox/Checkbox.vue
docs/app/pages/Components/Checkbox/examples/RegularCheckboxes.vue

docs(Checkbox): Object supported

---

src/components/MdCard/base.scss

fix(MdCard): prevent showing scrollbars

---

src/components/MdTable/MdTable.vue
src/components/MdTable/MdTableHead.vue

fix(MdTable) fixed header scroll issue

---

docs/app/pages/Components/Input/Input.vue
docs/app/pages/Components/Input/examples/AppBarNested.vue
docs/app/pages/Components/Input/examples/FieldVariations.vue
src/components/MdField/MdField.vue
src/components/MdField/MdTextarea/MdTextarea.vue
src/components/MdField/theme.scss
src/components/MdToolbar/MdToolbar.vue

- Bottom Line (with Floating Label)
- Box (with Floating Label)
- Raised (Inline Only)

feat(MdField) Field Variants

---

src/components/MdTable/MdTableCell.vue
src/components/MdTable/MdTableHead.vue

feat(MdTableCell): add `md-id` prop

---

src/components/MdField/MdField.vue

This PR will fix icons in selects are aligned to top

fix: icons in selects are aligned to top

---

docs/app/pages/Components/List/List.vue

Added missing api table for list and list item.

docs(MdList): add api table

---

src/components/MdMenu/MdMenuContent.vue

fix(MdMenuItem): fix vertical alignment in IE

---

docs/app/i18n/en-US/pages.js

fixed a typo in the English docs

---

src/components/MdField/MdField.vue

Fix issues caused by #1600
Fix issues mentioned in #1601 [comment](https://github.com/vuematerial/vue-material/pull/1601#issuecomment-376649139)
Fix prefix and suffix with icon and other variants issues

fix(MdField): fix textarea and inline issues

---

src/components/MdAutocomplete/MdAutocomplete.vue
src/components/MdField/MdFieldMixin.js
src/components/MdRipple/MdRipple.vue

fix: constructor name support for IE11

---

src/components/MdMenu/MdMenuContent.vue

fix(MdMenu): preventDefault only for specific keys

---

docs/app/pages/Components/Badge/Badge.vue
src/components/MdBadge/MdBadge.vue

note that style is not recommend because the same style will be applied on `.md-badge-content`

fix(MdBadge): custom class and style supported

---

src/components/MdTable/MdTable.vue

fix(MdTable): fix value condition

---

docs/app/pages/GettingStarted.vue

docs(GettingStarted): fix typo

---

docs/app/pages/Themes/Concepts.vue

docs(Concepts): fix typo

---

src/components/MdProgress/MdProgressBar/MdProgressBar.vue

fix(MdProgressBar): query style

---

src/components/MdButton/MdButton.vue

fix(MdButton): fab-bottom-center style

---

src/components/MdTabs/MdTabs.vue

fix(MdTabs): transparent content

---

docs/app/pages/Components/Datepicker/Datepicker.vue
src/components/MdDatepicker/MdDatepicker.vue

Fixes https://github.com/vuematerial/vue-material/issues/1602
Random note: Some tests failing on other components - do I have to fix these? Seems all the PRs are affected

feat(MdDatepicker): Debounce the conversion into a date object

---

src/components/MdSteppers/MdSteppers.vue

fix(MdSteppers): zero height in IE

---

docs/app/pages/Components/Chips/Chips.vue
docs/app/pages/Components/Chips/examples/ChipCustomTemplate.vue
docs/app/pages/Components/Chips/examples/DuplicatedFeedback.vue
docs/app/pages/Components/Chips/examples/Editable.vue
docs/app/pages/Components/Chips/examples/Format.vue
docs/app/pages/Components/Chips/examples/Static.vue
src/components/MdChips/MdChips.vue
src/components/MdField/MdField.vue

To support `MdChips` with all field variants (bottom-line, box and raised)

feat(MdChips): Support with field variants

---

docs/app/pages/Components/File/examples/FileField.vue
src/components/MdField/MdFile/MdFile.vue

To support with all field variants (bottom-line, box and raised)

feat(MdFile): Support with field variants

---

src/components/MdApp/MdApp.vue

fix(MdApp): fix typo

---

src/components/MdToolbar/MdToolbar.vue

fix toolbar button spacing

---

src/components/MdTable/MdTableHead.vue

fix(MdTableHead): fix sort indicator position

---

docs/app/pages/Components/Chips/Chips.vue

docs(Chips): typo fixed

---

docs/app/pages/GettingStarted.vue

Changed CDN urls from v1.0.0-beta-7 to latest

docs(GettingStarted): Changed CDN urls from v1.0.0-beta-7 to latest

---

docs/app/pages/Components/Checkbox/Checkbox.vue

Missed Object type added to doc description.

docs(Checkbox): Missed Object type added to doc description.

---

src/components/MdField/MdSelect/MdSelect.vue

fix(MdSelect): selected event before mounted

---

src/components/MdCard/MdCardExpand/MdCardExpandContent.vue

Auto fix `marginTop` while mutation observer triggered 
fix #1795

feat(MdCardExpandContent): reactive content

---

src/components/MdField/MdFile/MdFile.vue

fix(MdFile): disabled icon

---

src/components/MdTable/MdTable.vue

fix(MdTable): sort on created

---

src/components/MdMenu/MdMenuContent.vue

fix(MdMenuContent): destroy keydown listener on Esc

---

src/components/MdTabs/MdTabs.vue

fix(MdTabs): setupObservers on mounted immediately

---

src/components/MdAutocomplete/MdAutocomplete.vue

fix(MdAutocomplete): fix option selecting

---

src/components/MdList/MdListItem/MdListItem.vue
src/components/MdList/MdListItem/MdListItemFakeButton.vue

fix(MdListItem): allow multiple actions

---

docs/app/pages/GettingStarted.vue

Fix doc typo

---

src/components/MdApp/MdApp.vue

Fixes #1844 and Fixes #1827
It needs to be tested more before merge.

fix(MdApp): custom drawer component

---

docs/app/pages/Components/Button/Button.vue

docs(Button): escape a tag

---

docs/app/pages/UiElements/Elevation/Elevation.vue
docs/app/pages/UiElements/Layout/Layout.vue

docs(Elevation): Typos fixed.
docs(Layout): Documentation improved.

docs(Elevation and Layout): Typos fixed and improved documentation.

---

src/components/MdDialog/MdDialogContent.vue

fix(MdDialogContent): missing theme class

---

src/components/MdTable/MdTable.vue

fix(MdTable): recalculate fixed header width on data changes

---

ROADMAP.md

replace dead slack invite link with discord invite link and fix typo
related to #1914

docs(ROADMAP.md): replace dead slack invite link with discord invite link

---

docs/app/pages/GettingStarted.vue

Hello,
I suggest u add the include of default.css so people wont have to fiddle with until getting the components to work.

docs: add default theme as a suggestion

---

src/components/MdTable/MdTable.vue

Access to index

---

src/components/MdRadio/MdRadio.vue

fix(MdRadio): set checked property if radio is selected

---

docs/app/pages/WithRouter.vue

Update the Work With Vue Router page grammar

---

docs/app/pages/Components/Tabs/Tabs.vue

docs(Tabs): add prop `md-is-rtl` to tabs table component

---

src/components/MdSteppers/MdStep.vue

new version of #1816, conflicts resolved

fix(MdStep): set tabindex for not active step

---

src/components/MdMenu/MdMenuContent.vue

Reverts vuematerial/vue-material#2090

Revert "fix undefined contains method in IE11"

---

docs/app/pages/Components/Card/Card.vue

hey, i spotted a typo while reading through the docs, heres a pr with what i assume is the correct wording.
I've never done a pr before so let me know if i did something wrong.
Cheers

Fix typo in docs - Update Card.vue

---

.travis.yml
docs/app/template/MainFooter.vue
package-lock.json
package.json
yarn.lock

fix(node-sass): update node-sass

---

src/components/MdDatepicker/MdDatepicker.vue
src/components/MdDatepicker/MdDatepickerDialog.vue

Fix: Add placement to datepicker dialog

---

docs/app/pages/Components/Drawer/Drawer.vue
docs/app/pages/Components/Tabs/Tabs.vue

fix: typo fixed in docs

---

ROADMAP.md

Fixed typos

---

src/components/MdField/MdFieldMixin.js

This fix should fix the issue as well as keeping the intended behavior for all form components.

Fix for badInput in MdField mixin #2285

---

docs/app/components/CodesandboxEdit.vue
package-lock.json

Re-factored CodeSandBoxEdit.vue to work with current API

---

src/components/MdLayout/mixins.scss

fix(MdLayout): subtract md-layout-large by 16 instead of 17

---

docs/app/pages/PremiumThemes/PremiumThemes.vue
docs/app/template/MainHeader.vue
docs/app/template/MainNavContent.vue

feat: changed some broken links
